<?php 
 $GLOBALS["dictionary"]["quote_Quote"]=array (
  'table' => 'quote_quote',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_SUBJECT',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '200',
      'audited' => true,
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'comment' => 'The short description of the bug',
      'merge_filter' => 'disabled',
      'required' => true,
      'importable' => 'required',
      'comments' => 'The short description of the bug',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'quote_quote_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'quote_quote_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'quote_quote_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'quote_quote_number' => 
    array (
      'name' => 'quote_quote_number',
      'vname' => 'LBL_NUMBER',
      'type' => 'int',
      'readonly' => true,
      'len' => 11,
      'required' => true,
      'auto_increment' => true,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'comment' => 'Visual unique identifier',
      'duplicate_merge' => 'disabled',
      'disable_num_format' => true,
      'studio' => 
      array (
        'quickcreate' => false,
      ),
      'inline_edit' => false,
    ),
    'type' => 
    array (
      'name' => 'type',
      'vname' => 'LBL_TYPE',
      'type' => 'enum',
      'options' => 'quote_quote_type_dom',
      'len' => 255,
      'comment' => 'The type of issue (ex: issue, feature)',
      'merge_filter' => 'enabled',
    ),
    'status' => 
    array (
      'name' => 'status',
      'vname' => 'LBL_STATUS',
      'type' => 'enum',
      'options' => 'quote_quote_status_dom',
      'len' => 100,
      'audited' => true,
      'comment' => 'The status of the issue',
      'merge_filter' => 'enabled',
    ),
    'priority' => 
    array (
      'name' => 'priority',
      'vname' => 'LBL_PRIORITY',
      'type' => 'enum',
      'options' => 'quote_quote_priority_dom',
      'len' => 100,
      'audited' => true,
      'comment' => 'An indication of the priorty of the issue',
      'merge_filter' => 'enabled',
    ),
    'resolution' => 
    array (
      'name' => 'resolution',
      'vname' => 'LBL_RESOLUTION',
      'type' => 'enum',
      'options' => 'quote_quote_resolution_dom',
      'len' => 255,
      'audited' => true,
      'comment' => 'An indication of how the issue was resolved',
      'merge_filter' => 'enabled',
    ),
    'work_log' => 
    array (
      'name' => 'work_log',
      'vname' => 'LBL_WORK_LOG',
      'type' => 'text',
      'comment' => 'Free-form text used to denote activities of interest',
    ),
    'quotation_status' => 
    array (
      'required' => false,
      'name' => 'quotation_status',
      'vname' => 'LBL_QUOTATION_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'draft',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'quotation_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'discount' => 
    array (
      'required' => false,
      'name' => 'discount',
      'vname' => 'LBL_DISCOUNT',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default' => '0',
    ),
    'discount_checkbox' => 
    array (
      'required' => false,
      'name' => 'discount_checkbox',
      'vname' => 'LBL_DISCOUNT_CHECKBOX',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'insurance' => 
    array (
      'required' => false,
      'name' => 'insurance',
      'vname' => 'LBL_INSURANCE',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'terms_conditions' => 
    array (
      'required' => false,
      'name' => 'terms_conditions',
      'vname' => 'LBL_TERMS_CONDITIONS',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '10',
      'cols' => '80',
      'default' => '1. Goods once sold will not be taken back  or exchanged

2. The Vendor has the lien on the goods  supplied under this bill until the  payment of the bill is received.

3. Please Pay by cheque / DD only in favour of \'CLASSIC FLOORING\'S & INTERIORS PVT. LTD.\'.

4. 100% Advance against P.O

5. Wastage: Wastage if any, will be extra to client\'s account. . We would keep all debris outside the room installed .

6. Sub Floor: Should be absolutely dry, zero level absolutely moisture free.
  
7. Flooring\'s will be delivered in original packing. We sell by flooring by Boxes, rolls & Strips only.

8. All disputes are subject to Mumbai Jurisdiction.

9. Please refer our \'General Terms & Conditions\' of sales for all detailed conditions.

10. Goods would be delivered on the Ground Floor. Any loading/ unloading to subsequent floors would cost extra and as applicable.

11.  All changes under GST Will be extra and as applicable.

12. We would need your PAN no and GST no as applicable as per Government of India norms. 

13. Water and Power would be provided free of cost on site for self leveling and for vinyl welding as needed.

14. Post installation we will shift the debris outside as per customer instruction. Any additional house keeping would need to be done by the customer.



For Classic Flooring & Interiors Pvt. Ltd.



Authorized Signatory.',
      'inline_edit' => true,
    ),
    'quotation_category' => 
    array (
      'required' => false,
      'name' => 'quotation_category',
      'vname' => 'LBL_QUOTATION_CATEGORY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'Elastic_boost_options',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'covering_letter' => 
    array (
      'required' => false,
      'name' => 'covering_letter',
      'vname' => 'LBL_COVERING_LETTER',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
    ),
    'insurance_checkbox' => 
    array (
      'required' => false,
      'name' => 'insurance_checkbox',
      'vname' => 'LBL_INSURANCE_CHECKBOX',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'quote_type' => 
    array (
      'required' => false,
      'name' => 'quote_type',
      'vname' => 'LBL_QUOTE_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'Elastic_boost_options',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'quotation_date' => 
    array (
      'required' => false,
      'name' => 'quotation_date',
      'vname' => 'LBL_QUOTATION_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    ),
    'currency' => 
    array (
      'required' => false,
      'name' => 'currency',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'currency_id' => 
    array (
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
    ),
    'freight_charge' => 
    array (
      'required' => false,
      'name' => 'freight_charge',
      'vname' => 'LBL_FREIGHT_CHARGE',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'spares' => 
    array (
      'required' => false,
      'name' => 'spares',
      'vname' => 'LBL_SPARES',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'Elastic_boost_options',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'is_line' => 
    array (
      'required' => false,
      'name' => 'is_line',
      'vname' => 'LBL_IS_LINE',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '1',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'sub_total' => 
    array (
      'required' => false,
      'name' => 'sub_total',
      'vname' => 'LBL_SUB_TOTAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'precision' => '6',
      'min' => false,
      'max' => false,
    ),
    'discounted_total' => 
    array (
      'required' => false,
      'name' => 'discounted_total',
      'vname' => 'LBL_DISCOUNTED_TOTAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'precision' => '6',
      'min' => false,
      'max' => false,
    ),
    'new_subtotal' => 
    array (
      'required' => false,
      'name' => 'new_subtotal',
      'vname' => 'LBL_NEW_SUBTOTAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'precision' => '6',
      'min' => false,
      'max' => false,
    ),
    'grand_total' => 
    array (
      'required' => false,
      'name' => 'grand_total',
      'vname' => 'LBL_GRAND_TOTAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'precision' => '6',
      'min' => false,
      'max' => false,
    ),
    'total_tax' => 
    array (
      'required' => false,
      'name' => 'total_tax',
      'vname' => 'LBL_TOTAL_TAX',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'tax value of the whole record',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'default' => '0',
    ),
    'shipping_address_postalcode_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_postalcode_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '20',
      'size' => '20',
      'id' => 'quote_Quoteshipping_address_postalcode_c',
      'custom_module' => 'quote_Quote',
    ),
    'contact_id_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contact_id_c',
      'vname' => 'LBL_CONTACT_NAME_CONTACT_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'quote_Quotecontact_id_c',
      'custom_module' => 'quote_Quote',
    ),
    'structure_details_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Structure Details',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'structure_details_c',
      'vname' => 'LBL_STRUCTURE_DETAILS',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quotestructure_details_c',
      'custom_module' => 'quote_Quote',
    ),
    'shipping_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Other Charges',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_c',
      'vname' => 'LBL_SHIPPING',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quoteshipping_c',
      'custom_module' => 'quote_Quote',
    ),
    'purchase_order_number_c' => 
    array (
      'inline_edit' => 1,
      'type' => 'varchar',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'purchase_order_number_c',
      'vname' => 'LBL_PURCHASE_ORDER_NUMBER',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => NULL,
      'min' => false,
      'max' => false,
      'id' => 'quote_Quotepurchase_order_number_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_securitygroups_1' => 
    array (
      'name' => 'quote_quote_securitygroups_1',
      'type' => 'link',
      'relationship' => 'quote_quote_securitygroups_1',
      'source' => 'non-db',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTE_SECURITYGROUPS_1_FROM_SECURITYGROUPS_TITLE',
    ),
    'company_vat_details_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Company VAT Details',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'company_vat_details_c',
      'vname' => 'LBL_COMPANY_VAT_DETAILS',
      'type' => 'text',
      'massupdate' => '0',
      'default' => 'VAT TIN: 36703655325 
CST TIN: 29120351377
P.F.No.: MH/47797
ESIC No.: 31-48401-101
Service Tax No.: AAACC1815AST002',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
      'id' => 'quote_Quotecompany_vat_details_c',
      'custom_module' => 'quote_Quote',
    ),
    'old_pli_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Old PLI',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'old_pli_c',
      'vname' => 'LBL_OLD_PLI',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'quote_Quoteold_pli_c',
      'custom_module' => 'quote_Quote',
    ),
    'approval_status_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Approval Status',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'approval_status_c',
      'vname' => 'LBL_APPROVAL_STATUS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Approved',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'approval_status_dom',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quoteapproval_status_c',
      'custom_module' => 'quote_Quote',
    ),
    'payment_terms_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Payment Terms',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'payment_terms_c',
      'vname' => 'LBL_PAYMENT_TERMS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '100',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'payment_terms_0',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quotepayment_terms_c',
      'custom_module' => 'quote_Quote',
    ),
    'custom_quote_num_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Quote No',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'custom_quote_num_c',
      'vname' => 'LBL_CUSTOM_QUOTE_NUM_C',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotecustom_quote_num_c',
      'custom_module' => 'quote_Quote',
    ),
    'shipping_address_state_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_state_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quoteshipping_address_state_c',
      'custom_module' => 'quote_Quote',
    ),
    'accounts_quote_quote_1' => 
    array (
      'name' => 'accounts_quote_quote_1',
      'type' => 'link',
      'relationship' => 'accounts_quote_quote_1',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_ACCOUNTS_QUOTE_QUOTE_1_FROM_ACCOUNTS_TITLE',
      'id_name' => 'accounts_quote_quote_1accounts_ida',
    ),
    'accounts_quote_quote_1_name' => 
    array (
      'name' => 'accounts_quote_quote_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_ACCOUNTS_QUOTE_QUOTE_1_FROM_ACCOUNTS_TITLE',
      'save' => true,
      'id_name' => 'accounts_quote_quote_1accounts_ida',
      'link' => 'accounts_quote_quote_1',
      'table' => 'accounts',
      'module' => 'Accounts',
      'rname' => 'name',
    ),
    'accounts_quote_quote_1accounts_ida' => 
    array (
      'name' => 'accounts_quote_quote_1accounts_ida',
      'type' => 'link',
      'relationship' => 'accounts_quote_quote_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_ACCOUNTS_QUOTE_QUOTE_1_FROM_QUOTE_QUOTE_TITLE',
    ),
    'shipping_address_city_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_city_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quoteshipping_address_city_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_activities_1_tasks' => 
    array (
      'name' => 'quote_quote_activities_1_tasks',
      'type' => 'link',
      'relationship' => 'quote_quote_activities_1_tasks',
      'source' => 'non-db',
      'module' => 'Tasks',
      'bean_name' => 'Task',
      'vname' => 'LBL_QUOTE_QUOTE_ACTIVITIES_1_TASKS_FROM_TASKS_TITLE',
    ),
    'billing_address_city_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_city_c',
      'vname' => 'LBL_BILLING_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotebilling_address_city_c',
      'custom_module' => 'quote_Quote',
    ),
    'approved_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'approved',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'approved_c',
      'vname' => 'LBL_APPROVED',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quoteapproved_c',
      'custom_module' => 'quote_Quote',
    ),
    'shipping_1_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Shipping 1',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_1_c',
      'vname' => 'LBL_SHIPPING_1',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quoteshipping_1_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_activities_1_meetings' => 
    array (
      'name' => 'quote_quote_activities_1_meetings',
      'type' => 'link',
      'relationship' => 'quote_quote_activities_1_meetings',
      'source' => 'non-db',
      'module' => 'Meetings',
      'bean_name' => 'Meeting',
      'vname' => 'LBL_QUOTE_QUOTE_ACTIVITIES_1_MEETINGS_FROM_MEETINGS_TITLE',
    ),
    'decleration_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Decleration',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'decleration_c',
      'vname' => 'LBL_DECLERATION',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
      'id' => 'quote_Quotedecleration_c',
      'custom_module' => 'quote_Quote',
    ),
    'shipping_address_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Shipping Address',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_c',
      'vname' => 'LBL_SHIPPING_ADDRESS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quoteshipping_address_c',
      'custom_module' => 'quote_Quote',
    ),
    'other_charges_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Other Charges',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'other_charges_c',
      'vname' => 'LBL_OTHER_CHARGES',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quoteother_charges_c',
      'custom_module' => 'quote_Quote',
    ),
    'contact_name_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Billing Contact Name',
      'required' => false,
      'source' => 'non-db',
      'name' => 'contact_name_c',
      'vname' => 'LBL_CONTACT_NAME',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'contact_id_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'quote_Quotecontact_name_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_leads' => 
    array (
      'name' => 'quote_quote_leads',
      'type' => 'link',
      'relationship' => 'quote_quote_leads',
      'source' => 'non-db',
      'module' => 'Leads',
      'bean_name' => 'Lead',
      'vname' => 'LBL_QUOTE_QUOTE_LEADS_FROM_LEADS_TITLE',
      'id_name' => 'quote_quote_leadsleads_ida',
    ),
    'quote_quote_leads_name' => 
    array (
      'name' => 'quote_quote_leads_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_QUOTE_LEADS_FROM_LEADS_TITLE',
      'save' => true,
      'id_name' => 'quote_quote_leadsleads_ida',
      'link' => 'quote_quote_leads',
      'table' => 'leads',
      'module' => 'Leads',
      'rname' => 'name',
      'db_concat_fields' => 
      array (
        0 => 'first_name',
        1 => 'last_name',
      ),
    ),
    'quote_quote_leadsleads_ida' => 
    array (
      'name' => 'quote_quote_leadsleads_ida',
      'type' => 'link',
      'relationship' => 'quote_quote_leads',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTE_LEADS_FROM_QUOTE_QUOTE_TITLE',
    ),
    'packing_charges_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Packing Charges',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'packing_charges_c',
      'vname' => 'LBL_PACKING_CHARGES',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quotepacking_charges_c',
      'custom_module' => 'quote_Quote',
    ),
    'billing_address_postalcode_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_postalcode_c',
      'vname' => 'LBL_BILLING_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '20',
      'size' => '20',
      'id' => 'quote_Quotebilling_address_postalcode_c',
      'custom_module' => 'quote_Quote',
    ),
    'valid_until_c' => 
    array (
      'inline_edit' => 1,
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'valid_until_c',
      'vname' => 'LBL_VALID_UNTIL',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'quote_Quotevalid_until_c',
      'custom_module' => 'quote_Quote',
    ),
    'certify_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Certify',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'certify_c',
      'vname' => 'LBL_CERTIFY',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '6',
      'cols' => '80',
      'id' => 'quote_Quotecertify_c',
      'custom_module' => 'quote_Quote',
    ),
    'contact_id1_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contact_id1_c',
      'vname' => 'LBL_CONTACT_NAME_SHIPPING_CONTACT_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'quote_Quotecontact_id1_c',
      'custom_module' => 'quote_Quote',
    ),
    'team_list_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'team_list_c',
      'vname' => 'LBL_TEAM_LIST',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Bangalore1',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'team_list_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quoteteam_list_c',
      'custom_module' => 'quote_Quote',
    ),
    'billing_address_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Billing Address',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_c',
      'vname' => 'LBL_BILLING_ADDRESS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotebilling_address_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_line_item_layout_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Quote Line Item Layout',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'quote_line_item_layout_c',
      'vname' => 'LBL_QUOTE_LINE_ITEM_LAYOUT',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotequote_line_item_layout_c',
      'custom_module' => 'quote_Quote',
    ),
    'customer_type_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Customer Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'customer_type_c',
      'vname' => 'LBL_CUSTOMER_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'Elastic_boost_options',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quotecustomer_type_c',
      'custom_module' => 'quote_Quote',
    ),
    'new_pli_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'New PLI',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'new_pli_c',
      'vname' => 'LBL_NEW_PLI',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'quote_Quotenew_pli_c',
      'custom_module' => 'quote_Quote',
    ),
    'pdf_type_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'PDF Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'pdf_type_c',
      'vname' => 'LBL_PDF_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Quote',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'pdf_type_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quotepdf_type_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_activities_1_calls' => 
    array (
      'name' => 'quote_quote_activities_1_calls',
      'type' => 'link',
      'relationship' => 'quote_quote_activities_1_calls',
      'source' => 'non-db',
      'module' => 'Calls',
      'bean_name' => 'Call',
      'vname' => 'LBL_QUOTE_QUOTE_ACTIVITIES_1_CALLS_FROM_CALLS_TITLE',
    ),
    'quote_quote_activities_1_emails' => 
    array (
      'name' => 'quote_quote_activities_1_emails',
      'type' => 'link',
      'relationship' => 'quote_quote_activities_1_emails',
      'source' => 'non-db',
      'module' => 'Emails',
      'bean_name' => 'Email',
      'vname' => 'LBL_QUOTE_QUOTE_ACTIVITIES_1_EMAILS_FROM_EMAILS_TITLE',
    ),
    'shipping_address_country_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Shipping Address Country',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_country_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => 'India',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quoteshipping_address_country_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_activities_1_notes' => 
    array (
      'name' => 'quote_quote_activities_1_notes',
      'type' => 'link',
      'relationship' => 'quote_quote_activities_1_notes',
      'source' => 'non-db',
      'module' => 'Notes',
      'bean_name' => 'Note',
      'vname' => 'LBL_QUOTE_QUOTE_ACTIVITIES_1_NOTES_FROM_NOTES_TITLE',
    ),
    'billing_address_state_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_state_c',
      'vname' => 'LBL_BILLING_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotebilling_address_state_c',
      'custom_module' => 'quote_Quote',
    ),
    'shipping_2_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Shipping 2',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_2_c',
      'vname' => 'LBL_SHIPPING_2',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quoteshipping_2_c',
      'custom_module' => 'quote_Quote',
    ),
    'copy_address_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Copy Address',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'copy_address_c',
      'vname' => 'LBL_COPY_ADDRESS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotecopy_address_c',
      'custom_module' => 'quote_Quote',
    ),
    'contact_name_shipping_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Shipping Contact Name',
      'required' => false,
      'source' => 'non-db',
      'name' => 'contact_name_shipping_c',
      'vname' => 'LBL_CONTACT_NAME_SHIPPING',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'contact_id1_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'quote_Quotecontact_name_shipping_c',
      'custom_module' => 'quote_Quote',
    ),
    'approval_issue_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Approval Issue',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'approval_issue_c',
      'vname' => 'LBL_APPROVAL_ISSUE',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '60',
      'id' => 'quote_Quoteapproval_issue_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_opportunities' => 
    array (
      'name' => 'quote_quote_opportunities',
      'type' => 'link',
      'relationship' => 'quote_quote_opportunities',
      'source' => 'non-db',
      'module' => 'Opportunities',
      'bean_name' => 'Opportunity',
      'vname' => 'LBL_QUOTE_QUOTE_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
      'id_name' => 'quote_quote_opportunitiesopportunities_ida',
    ),
    'quote_quote_opportunities_name' => 
    array (
      'name' => 'quote_quote_opportunities_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_QUOTE_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
      'save' => true,
      'id_name' => 'quote_quote_opportunitiesopportunities_ida',
      'link' => 'quote_quote_opportunities',
      'table' => 'opportunities',
      'module' => 'Opportunities',
      'rname' => 'name',
    ),
    'quote_quote_opportunitiesopportunities_ida' => 
    array (
      'name' => 'quote_quote_opportunitiesopportunities_ida',
      'type' => 'link',
      'relationship' => 'quote_quote_opportunities',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTE_OPPORTUNITIES_FROM_QUOTE_QUOTE_TITLE',
    ),
    'original_p_o_date_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'original_p_o_date_c',
      'vname' => 'LBL_ORIGINAL_P_O_DATE',
      'type' => 'date',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'quote_Quoteoriginal_p_o_date_c',
      'custom_module' => 'quote_Quote',
    ),
    'quote_quote_accounts' => 
    array (
      'name' => 'quote_quote_accounts',
      'type' => 'link',
      'relationship' => 'quote_quote_accounts',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_QUOTE_QUOTE_ACCOUNTS_FROM_ACCOUNTS_TITLE',
      'id_name' => 'quote_quote_accountsaccounts_ida',
    ),
    'quote_quote_accounts_name' => 
    array (
      'name' => 'quote_quote_accounts_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_QUOTE_ACCOUNTS_FROM_ACCOUNTS_TITLE',
      'save' => true,
      'id_name' => 'quote_quote_accountsaccounts_ida',
      'link' => 'quote_quote_accounts',
      'table' => 'accounts',
      'module' => 'Accounts',
      'rname' => 'name',
    ),
    'quote_quote_accountsaccounts_ida' => 
    array (
      'name' => 'quote_quote_accountsaccounts_ida',
      'type' => 'link',
      'relationship' => 'quote_quote_accounts',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTE_ACCOUNTS_FROM_QUOTE_QUOTE_TITLE',
    ),
    'billing_address_country_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Billing Address Country',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_country_c',
      'vname' => 'LBL_BILLING_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => 'India',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotebilling_address_country_c',
      'custom_module' => 'quote_Quote',
    ),
    'freight_charges_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Freight Charges',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'freight_charges_c',
      'vname' => 'LBL_FREIGHT_CHARGES',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quotefreight_charges_c',
      'custom_module' => 'quote_Quote',
    ),
    'branch_c' => 
    array (
      'inline_edit' => 1,
      'labelValue' => 'Branch',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'branch_c',
      'vname' => 'LBL_BRANCH',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'branch_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quotebranch_c',
      'custom_module' => 'quote_Quote',
    ),
    'loading_unloading_charges_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Loading & unloading Charges',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'loading_unloading_charges_c',
      'vname' => 'LBL_LOADING_UNLOADING_CHARGES_C',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'quote_Quoteloading_unloading_charges_c',
      'custom_module' => 'quote_Quote',
    ),
    'unregistered_user_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Unregistered Customer',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'unregistered_user_c',
      'vname' => 'LBL_UNREGISTERED_USER',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quoteunregistered_user_c',
      'custom_module' => 'quote_Quote',
    ),
    'cess_amount_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'kerala Cess 1%',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'cess_amount_c',
      'vname' => 'LBL_CESS_AMOUNT',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'quote_Quotecess_amount_c',
      'custom_module' => 'quote_Quote',
    ),
    'dutyfree_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Duty Free',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'dutyfree_c',
      'vname' => 'LBL_DUTYFREE',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'dutyfree_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Quotedutyfree_c',
      'custom_module' => 'quote_Quote',
    ),
  ),
  'relationships' => 
  array (
    'quote_quote_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Quote',
      'rhs_table' => 'quote_quote',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'quote_quote_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Quote',
      'rhs_table' => 'quote_quote',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'quote_quote_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Quote',
      'rhs_table' => 'quote_quote',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'quote_quotepk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
    'number' => 
    array (
      'name' => 'quote_quotenumk',
      'type' => 'unique',
      'fields' => 
      array (
        0 => 'quote_quote_number',
      ),
    ),
  ),
  'templates' => 
  array (
    'issue' => 'issue',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);