<?php 
 $GLOBALS["dictionary"]["quote_Quotes"]=array (
  'table' => 'quote_quotes',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_SUBJECT',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'audited' => true,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'comment' => 'The short description of the bug',
      'merge_filter' => 'selected',
      'required' => true,
      'importable' => 'required',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'quote_quotes_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'quote_quotes_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'quote_quotes_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'quote_quotes_number' => 
    array (
      'name' => 'quote_quotes_number',
      'vname' => 'LBL_NUMBER',
      'type' => 'int',
      'len' => '11',
      'required' => true,
      'auto_increment' => true,
      'unified_search' => true,
      'comment' => 'Visual unique identifier',
      'duplicate_merge' => 'disabled',
      'disable_num_format' => '',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
    ),
    'type' => 
    array (
      'name' => 'type',
      'vname' => 'LBL_TYPE',
      'type' => 'enum',
      'options' => 'quote_quotes_type_dom',
      'len' => 255,
      'comment' => 'The type of issue (ex: issue, feature)',
      'merge_filter' => 'enabled',
    ),
    'status' => 
    array (
      'name' => 'status',
      'vname' => 'LBL_STATUS',
      'type' => 'enum',
      'options' => 'quote_quotes_status_dom',
      'len' => 100,
      'audited' => true,
      'comment' => 'The status of the issue',
      'merge_filter' => 'enabled',
    ),
    'priority' => 
    array (
      'name' => 'priority',
      'vname' => 'LBL_PRIORITY',
      'type' => 'enum',
      'options' => 'quote_quotes_priority_dom',
      'len' => 100,
      'audited' => true,
      'comment' => 'An indication of the priorty of the issue',
      'merge_filter' => 'enabled',
    ),
    'resolution' => 
    array (
      'name' => 'resolution',
      'vname' => 'LBL_RESOLUTION',
      'type' => 'enum',
      'options' => 'quote_quotes_resolution_dom',
      'len' => 255,
      'audited' => true,
      'comment' => 'An indication of how the issue was resolved',
      'merge_filter' => 'enabled',
    ),
    'work_log' => 
    array (
      'name' => 'work_log',
      'vname' => 'LBL_WORK_LOG',
      'type' => 'text',
      'comment' => 'Free-form text used to denote activities of interest',
    ),
    'quotation_status' => 
    array (
      'required' => false,
      'name' => 'quotation_status',
      'vname' => 'LBL_QUOTATION_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'draft',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'quotation_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'tax' => 
    array (
      'required' => false,
      'name' => 'tax',
      'vname' => 'LBL_TAX',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'VAT_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'discount' => 
    array (
      'required' => false,
      'name' => 'discount',
      'vname' => 'LBL_DISCOUNT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '11',
      'size' => '20',
    ),
    'discount_checkbox' => 
    array (
      'required' => false,
      'name' => 'discount_checkbox',
      'vname' => 'LBL_DISCOUNT_CHECKBOX',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'insurance' => 
    array (
      'required' => false,
      'name' => 'insurance',
      'vname' => 'LBL_INSURANCE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '11',
      'size' => '20',
    ),
    'terms_conditions' => 
    array (
      'required' => false,
      'name' => 'terms_conditions',
      'vname' => 'LBL_TERMS_CONDITIONS',
      'type' => 'text',
      'massupdate' => 0,
      'default' => '1. Delivery: Delivery in 8 weeks from the date of receipt of order and advance.
2. Payment terms: 50% on order and balance payable prior to dispatch.
3. This quotation is valid for 30 days
4. One year warranty against manufacturing defects.
5. Prices quoted are Ex-Bangalore India.',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '7',
      'cols' => '45',
    ),
    'quotation_category' => 
    array (
      'required' => false,
      'name' => 'quotation_category',
      'vname' => 'LBL_QUOTATION_CATEGORY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'bo',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'quote_category_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'covering_letter' => 
    array (
      'required' => false,
      'name' => 'covering_letter',
      'vname' => 'LBL_COVERING_LETTER',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '5',
      'cols' => '35',
    ),
    'insurance_checkbox' => 
    array (
      'required' => false,
      'name' => 'insurance_checkbox',
      'vname' => 'LBL_INSURANCE_CHECKBOX',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'quote_products_id_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product1' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product1',
      'vname' => 'LBL_PRODUCT1',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'prod1_quantity' => 
    array (
      'required' => false,
      'name' => 'prod1_quantity',
      'vname' => 'LBL_PROD1_QUANTITY',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'default' => '1',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '11',
      'size' => '20',
      'disable_num_format' => '',
    ),
    'prod1_cost' => 
    array (
      'required' => false,
      'name' => 'prod1_cost',
      'vname' => 'LBL_PROD1_COST',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '11',
      'size' => '20',
      'disable_num_format' => '',
    ),
    'quote_products_id1_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id1_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'default' => '1',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'sm_quotes_id_c' => 
    array (
      'required' => false,
      'name' => 'sm_quotes_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'quote_products_id2_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id2_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product2' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product2',
      'vname' => 'LBL_PRODUCT2',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id2_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quote_products_id3_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id3_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product3' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product3',
      'vname' => 'LBL_PRODUCT3',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id3_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quote_products_id4_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id4_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product4' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product4',
      'vname' => 'LBL_PRODUCT4',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id4_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quote_products_id5_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id5_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product5' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product5',
      'vname' => 'LBL_PRODUCT5',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id5_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quote_products_id6_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id6_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product6' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product6',
      'vname' => 'LBL_PRODUCT6',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id6_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quantity1' => 
    array (
      'required' => false,
      'name' => 'quantity1',
      'vname' => 'LBL_QUANTITY1',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'quantity2' => 
    array (
      'required' => false,
      'name' => 'quantity2',
      'vname' => 'LBL_QUANTITY2',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quote_products_id7_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id7_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product7' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product7',
      'vname' => 'LBL_PRODUCT7',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id7_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quantity3' => 
    array (
      'required' => false,
      'name' => 'quantity3',
      'vname' => 'LBL_QUANTITY3',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quote_products_id8_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id8_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product8' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product8',
      'vname' => 'LBL_PRODUCT8',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id8_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quantity4' => 
    array (
      'required' => false,
      'name' => 'quantity4',
      'vname' => 'LBL_QUANTITY4',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity5' => 
    array (
      'required' => false,
      'name' => 'quantity5',
      'vname' => 'LBL_QUANTITY5',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quote_products_id9_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id9_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product9' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product9',
      'vname' => 'LBL_PRODUCT9',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id9_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quantity6' => 
    array (
      'required' => false,
      'name' => 'quantity6',
      'vname' => 'LBL_QUANTITY6',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quote_products_id10_c' => 
    array (
      'required' => false,
      'name' => 'quote_products_id10_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
    ),
    'product10' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'product10',
      'vname' => 'LBL_PRODUCT10',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'id_name' => 'quote_products_id10_c',
      'ext2' => 'quote_Products',
      'module' => 'quote_Products',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'quantity7' => 
    array (
      'required' => false,
      'name' => 'quantity7',
      'vname' => 'LBL_QUANTITY7',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity8' => 
    array (
      'required' => false,
      'name' => 'quantity8',
      'vname' => 'LBL_QUANTITY8',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity9' => 
    array (
      'required' => false,
      'name' => 'quantity9',
      'vname' => 'LBL_QUANTITY9',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'product11' => 
    array (
      'required' => false,
      'name' => 'product11',
      'vname' => 'LBL_PRODUCT11',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity10' => 
    array (
      'required' => false,
      'name' => 'quantity10',
      'vname' => 'LBL_QUANTITY10',
      'type' => 'varchar',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product12' => 
    array (
      'required' => false,
      'name' => 'product12',
      'vname' => 'LBL_PRODUCT12',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product13' => 
    array (
      'required' => false,
      'name' => 'product13',
      'vname' => 'LBL_PRODUCT13',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity11' => 
    array (
      'required' => false,
      'name' => 'quantity11',
      'vname' => 'LBL_QUANTITY11',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity12' => 
    array (
      'required' => false,
      'name' => 'quantity12',
      'vname' => 'LBL_QUANTITY12',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity13' => 
    array (
      'required' => false,
      'name' => 'quantity13',
      'vname' => 'LBL_QUANTITY13',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity14' => 
    array (
      'required' => false,
      'name' => 'quantity14',
      'vname' => 'LBL_QUANTITY14',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity15' => 
    array (
      'required' => false,
      'name' => 'quantity15',
      'vname' => 'LBL_QUANTITY15',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'product14' => 
    array (
      'required' => false,
      'name' => 'product14',
      'vname' => 'LBL_PRODUCT14',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity16' => 
    array (
      'required' => false,
      'name' => 'quantity16',
      'vname' => 'LBL_QUANTITY16',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product15' => 
    array (
      'required' => false,
      'name' => 'product15',
      'vname' => 'LBL_PRODUCT15',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity17' => 
    array (
      'required' => false,
      'name' => 'quantity17',
      'vname' => 'LBL_QUANTITY17',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity18' => 
    array (
      'required' => false,
      'name' => 'quantity18',
      'vname' => 'LBL_QUANTITY18',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'product16' => 
    array (
      'required' => false,
      'name' => 'product16',
      'vname' => 'LBL_PRODUCT16',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity19' => 
    array (
      'required' => false,
      'name' => 'quantity19',
      'vname' => 'LBL_QUANTITY19',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product17' => 
    array (
      'required' => false,
      'name' => 'product17',
      'vname' => 'LBL_PRODUCT17',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product18' => 
    array (
      'required' => false,
      'name' => 'product18',
      'vname' => 'LBL_PRODUCT18',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity20' => 
    array (
      'required' => false,
      'name' => 'quantity20',
      'vname' => 'LBL_QUANTITY20',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product19' => 
    array (
      'required' => false,
      'name' => 'product19',
      'vname' => 'LBL_PRODUCT19',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity21' => 
    array (
      'required' => false,
      'name' => 'quantity21',
      'vname' => 'LBL_QUANTITY21',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity22' => 
    array (
      'required' => false,
      'name' => 'quantity22',
      'vname' => 'LBL_QUANTITY22',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'quantity23' => 
    array (
      'required' => false,
      'name' => 'quantity23',
      'vname' => 'LBL_QUANTITY23',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity24' => 
    array (
      'required' => false,
      'name' => 'quantity24',
      'vname' => 'LBL_QUANTITY24',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity25' => 
    array (
      'required' => false,
      'name' => 'quantity25',
      'vname' => 'LBL_QUANTITY25',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'product20' => 
    array (
      'required' => false,
      'name' => 'product20',
      'vname' => 'LBL_PRODUCT20',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity26' => 
    array (
      'required' => false,
      'name' => 'quantity26',
      'vname' => 'LBL_QUANTITY26',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity27' => 
    array (
      'required' => false,
      'name' => 'quantity27',
      'vname' => 'LBL_QUANTITY27',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product21' => 
    array (
      'required' => false,
      'name' => 'product21',
      'vname' => 'LBL_PRODUCT21',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity28' => 
    array (
      'required' => false,
      'name' => 'quantity28',
      'vname' => 'LBL_QUANTITY28',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'product22' => 
    array (
      'required' => false,
      'name' => 'product22',
      'vname' => 'LBL_PRODUCT22',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product23' => 
    array (
      'required' => false,
      'name' => 'product23',
      'vname' => 'LBL_PRODUCT23',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity29' => 
    array (
      'required' => false,
      'name' => 'quantity29',
      'vname' => 'LBL_QUANTITY29',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'product24' => 
    array (
      'required' => false,
      'name' => 'product24',
      'vname' => 'LBL_PRODUCT24',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity30' => 
    array (
      'required' => false,
      'name' => 'quantity30',
      'vname' => 'LBL_QUANTITY30',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product25' => 
    array (
      'required' => false,
      'name' => 'product25',
      'vname' => 'LBL_PRODUCT25',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity31' => 
    array (
      'required' => false,
      'name' => 'quantity31',
      'vname' => 'LBL_QUANTITY31',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity32' => 
    array (
      'required' => false,
      'name' => 'quantity32',
      'vname' => 'LBL_QUANTITY32',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'quantity33' => 
    array (
      'required' => false,
      'name' => 'quantity33',
      'vname' => 'LBL_QUANTITY33',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity34' => 
    array (
      'required' => false,
      'name' => 'quantity34',
      'vname' => 'LBL_QUANTITY34',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quantity35' => 
    array (
      'required' => false,
      'name' => 'quantity35',
      'vname' => 'LBL_QUANTITY35',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product26' => 
    array (
      'required' => false,
      'name' => 'product26',
      'vname' => 'LBL_PRODUCT26',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product27' => 
    array (
      'required' => false,
      'name' => 'product27',
      'vname' => 'LBL_PRODUCT27',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product28' => 
    array (
      'required' => false,
      'name' => 'product28',
      'vname' => 'LBL_PRODUCT28',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product29' => 
    array (
      'required' => false,
      'name' => 'product29',
      'vname' => 'LBL_PRODUCT29',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product30' => 
    array (
      'required' => false,
      'name' => 'product30',
      'vname' => 'LBL_PRODUCT30',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product31' => 
    array (
      'required' => false,
      'name' => 'product31',
      'vname' => 'LBL_PRODUCT31',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product32' => 
    array (
      'required' => false,
      'name' => 'product32',
      'vname' => 'LBL_PRODUCT32',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product33' => 
    array (
      'required' => false,
      'name' => 'product33',
      'vname' => 'LBL_PRODUCT33',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product34' => 
    array (
      'required' => false,
      'name' => 'product34',
      'vname' => 'LBL_PRODUCT34',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'product35' => 
    array (
      'required' => false,
      'name' => 'product35',
      'vname' => 'LBL_PRODUCT35',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost1' => 
    array (
      'required' => false,
      'name' => 'cost1',
      'vname' => 'LBL_COST1',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost3' => 
    array (
      'required' => false,
      'name' => 'cost3',
      'vname' => 'LBL_COST3',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost4' => 
    array (
      'required' => false,
      'name' => 'cost4',
      'vname' => 'LBL_COST4',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost5' => 
    array (
      'required' => false,
      'name' => 'cost5',
      'vname' => 'LBL_COST5',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost6' => 
    array (
      'required' => false,
      'name' => 'cost6',
      'vname' => 'LBL_COST6',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost7' => 
    array (
      'required' => false,
      'name' => 'cost7',
      'vname' => 'LBL_COST7',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost8' => 
    array (
      'required' => false,
      'name' => 'cost8',
      'vname' => 'LBL_COST8',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost9' => 
    array (
      'required' => false,
      'name' => 'cost9',
      'vname' => 'LBL_COST9',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'cost10' => 
    array (
      'required' => false,
      'name' => 'cost10',
      'vname' => 'LBL_COST10',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price1' => 
    array (
      'required' => false,
      'name' => 'price1',
      'vname' => 'LBL_PRICE1',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price2' => 
    array (
      'required' => false,
      'name' => 'price2',
      'vname' => 'LBL_PRICE2',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price3' => 
    array (
      'required' => false,
      'name' => 'price3',
      'vname' => 'LBL_PRICE3',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price4' => 
    array (
      'required' => false,
      'name' => 'price4',
      'vname' => 'LBL_PRICE4',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price5' => 
    array (
      'required' => false,
      'name' => 'price5',
      'vname' => 'LBL_PRICE5',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price6' => 
    array (
      'required' => false,
      'name' => 'price6',
      'vname' => 'LBL_PRICE6',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price7' => 
    array (
      'required' => false,
      'name' => 'price7',
      'vname' => 'LBL_PRICE7',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'price8' => 
    array (
      'required' => false,
      'name' => 'price8',
      'vname' => 'LBL_PRICE8',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price9' => 
    array (
      'required' => false,
      'name' => 'price9',
      'vname' => 'LBL_PRICE9',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price10' => 
    array (
      'required' => false,
      'name' => 'price10',
      'vname' => 'LBL_PRICE10',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price11' => 
    array (
      'required' => false,
      'name' => 'price11',
      'vname' => 'LBL_PRICE11',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price12' => 
    array (
      'required' => false,
      'name' => 'price12',
      'vname' => 'LBL_PRICE12',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price13' => 
    array (
      'required' => false,
      'name' => 'price13',
      'vname' => 'LBL_PRICE13',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price14' => 
    array (
      'required' => false,
      'name' => 'price14',
      'vname' => 'LBL_PRICE14',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price15' => 
    array (
      'required' => false,
      'name' => 'price15',
      'vname' => 'LBL_PRICE15',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price16' => 
    array (
      'required' => false,
      'name' => 'price16',
      'vname' => 'LBL_PRICE16',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price17' => 
    array (
      'required' => false,
      'name' => 'price17',
      'vname' => 'LBL_PRICE17',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price18' => 
    array (
      'required' => false,
      'name' => 'price18',
      'vname' => 'LBL_PRICE18',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price19' => 
    array (
      'required' => false,
      'name' => 'price19',
      'vname' => 'LBL_PRICE19',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price20' => 
    array (
      'required' => false,
      'name' => 'price20',
      'vname' => 'LBL_PRICE20',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price21' => 
    array (
      'required' => false,
      'name' => 'price21',
      'vname' => 'LBL_PRICE21',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
    ),
    'price22' => 
    array (
      'required' => false,
      'name' => 'price22',
      'vname' => 'LBL_PRICE22',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price23' => 
    array (
      'required' => false,
      'name' => 'price23',
      'vname' => 'LBL_PRICE23',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price24' => 
    array (
      'required' => false,
      'name' => 'price24',
      'vname' => 'LBL_PRICE24',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'price25' => 
    array (
      'required' => false,
      'name' => 'price25',
      'vname' => 'LBL_PRICE25',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quote_type' => 
    array (
      'required' => true,
      'name' => 'quote_type',
      'vname' => 'LBL_QUOTE_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'quote_type_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'spares' => 
    array (
      'required' => false,
      'name' => 'spares',
      'vname' => 'LBL_SPARES',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'Spares_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'currency' => 
    array (
      'required' => false,
      'name' => 'currency',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 26,
      'size' => '20',
    ),
    'currency_id' => 
    array (
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'len' => 36,
      'size' => '20',
      'studio' => 'hidden',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
    ),
    'freight_charge' => 
    array (
      'required' => false,
      'name' => 'freight_charge',
      'vname' => 'LBL_FREIGHT_CHARGE',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'disable_num_format' => '',
      'validation' => 
      array (
        'type' => 'range',
        'min' => 0,
        'max' => '100000000000000000',
      ),
    ),
    'sales_quote_no' => 
    array (
      'required' => false,
      'name' => 'sales_quote_no',
      'vname' => 'LBL_SALES_QUOTE_NO',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => 'Quote number for sales quote auto incrementing',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'disable_num_format' => '',
    ),
    'service_quotes_no' => 
    array (
      'required' => false,
      'name' => 'service_quotes_no',
      'vname' => 'LBL_SERVICE_QUOTES_NO',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => 'Quote no for service quote auto incrementing',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'disable_num_format' => '',
    ),
    'cost2' => 
    array (
      'required' => false,
      'name' => 'cost2',
      'vname' => 'LBL_COST2',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '100',
      'size' => '20',
    ),
    'quotation_date' => 
    array (
      'required' => false,
      'name' => 'quotation_date',
      'vname' => 'LBL_QUOTATION_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
    ),
    'quote_quotes_opportunities' => 
    array (
      'name' => 'quote_quotes_opportunities',
      'type' => 'link',
      'relationship' => 'quote_quotes_opportunities',
      'source' => 'non-db',
      'module' => 'Opportunities',
      'bean_name' => 'Opportunity',
      'vname' => 'LBL_QUOTE_QUOTES_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
      'id_name' => 'quote_quotes_opportunitiesopportunities_ida',
    ),
    'quote_quotes_opportunities_name' => 
    array (
      'name' => 'quote_quotes_opportunities_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_QUOTES_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
      'save' => true,
      'id_name' => 'quote_quotes_opportunitiesopportunities_ida',
      'link' => 'quote_quotes_opportunities',
      'table' => 'opportunities',
      'module' => 'Opportunities',
      'rname' => 'name',
    ),
    'quote_quotes_opportunitiesopportunities_ida' => 
    array (
      'name' => 'quote_quotes_opportunitiesopportunities_ida',
      'type' => 'link',
      'relationship' => 'quote_quotes_opportunities',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTES_OPPORTUNITIES_FROM_QUOTE_QUOTES_TITLE',
    ),
    'quote_quotes_accounts' => 
    array (
      'name' => 'quote_quotes_accounts',
      'type' => 'link',
      'relationship' => 'quote_quotes_accounts',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_QUOTE_QUOTES_ACCOUNTS_FROM_ACCOUNTS_TITLE',
      'id_name' => 'quote_quotes_accountsaccounts_ida',
    ),
    'quote_quotes_accounts_name' => 
    array (
      'name' => 'quote_quotes_accounts_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_QUOTES_ACCOUNTS_FROM_ACCOUNTS_TITLE',
      'save' => true,
      'id_name' => 'quote_quotes_accountsaccounts_ida',
      'link' => 'quote_quotes_accounts',
      'table' => 'accounts',
      'module' => 'Accounts',
      'rname' => 'name',
    ),
    'quote_quotes_accountsaccounts_ida' => 
    array (
      'name' => 'quote_quotes_accountsaccounts_ida',
      'type' => 'link',
      'relationship' => 'quote_quotes_accounts',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTES_ACCOUNTS_FROM_QUOTE_QUOTES_TITLE',
    ),
    'quote_quotes_leads' => 
    array (
      'name' => 'quote_quotes_leads',
      'type' => 'link',
      'relationship' => 'quote_quotes_leads',
      'source' => 'non-db',
      'module' => 'Leads',
      'bean_name' => 'Lead',
      'vname' => 'LBL_QUOTE_QUOTES_LEADS_FROM_LEADS_TITLE',
      'id_name' => 'quote_quotes_leadsleads_ida',
    ),
    'quote_quotes_leads_name' => 
    array (
      'name' => 'quote_quotes_leads_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_QUOTES_LEADS_FROM_LEADS_TITLE',
      'save' => true,
      'id_name' => 'quote_quotes_leadsleads_ida',
      'link' => 'quote_quotes_leads',
      'table' => 'leads',
      'module' => 'Leads',
      'rname' => 'name',
      'db_concat_fields' => 
      array (
        0 => 'first_name',
        1 => 'last_name',
      ),
    ),
    'quote_quotes_leadsleads_ida' => 
    array (
      'name' => 'quote_quotes_leadsleads_ida',
      'type' => 'link',
      'relationship' => 'quote_quotes_leads',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTES_LEADS_FROM_QUOTE_QUOTES_TITLE',
    ),
    'billing_address_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_c',
      'vname' => 'LBL_BILLING_ADDRESS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotesbilling_address_c',
      'custom_module' => 'quote_Quotes',
    ),
    'billing_address_city_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_city_c',
      'vname' => 'LBL_BILLING_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotesbilling_address_city_c',
      'custom_module' => 'quote_Quotes',
    ),
    'billing_address_country_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_country_c',
      'vname' => 'LBL_BILLING_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotesbilling_address_country_c',
      'custom_module' => 'quote_Quotes',
    ),
    'billing_address_postalcode_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_postalcode_c',
      'vname' => 'LBL_BILLING_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '20',
      'size' => '20',
      'id' => 'quote_Quotesbilling_address_postalcode_c',
      'custom_module' => 'quote_Quotes',
    ),
    'billing_address_state_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billing_address_state_c',
      'vname' => 'LBL_BILLING_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotesbilling_address_state_c',
      'custom_module' => 'quote_Quotes',
    ),
    'payment_terms_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'payment_terms_c',
      'vname' => 'LBL_PAYMENT_TERMS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '100',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'payment_terms_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'quote_Quotespayment_terms_c',
      'custom_module' => 'quote_Quotes',
    ),
    'purchase_order_no_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'purchase_order_no_c',
      'vname' => 'LBL_PURCHASE_ORDER_NO',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotespurchase_order_no_c',
      'custom_module' => 'quote_Quotes',
    ),
    'p_o_date_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'p_o_date_c',
      'vname' => 'LBL_P_O_DATE',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'quote_Quotesp_o_date_c',
      'custom_module' => 'quote_Quotes',
    ),
    'shipping_address_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_c',
      'vname' => 'LBL_SHIPPING_ADDRESS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Quotesshipping_address_c',
      'custom_module' => 'quote_Quotes',
    ),
    'shipping_address_city_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_city_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotesshipping_address_city_c',
      'custom_module' => 'quote_Quotes',
    ),
    'shipping_address_country_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_country_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotesshipping_address_country_c',
      'custom_module' => 'quote_Quotes',
    ),
    'shipping_address_postalcode_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_postalcode_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '20',
      'size' => '20',
      'id' => 'quote_Quotesshipping_address_postalcode_c',
      'custom_module' => 'quote_Quotes',
    ),
    'shipping_address_state_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'shipping_address_state_c',
      'vname' => 'LBL_SHIPPING_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'id' => 'quote_Quotesshipping_address_state_c',
      'custom_module' => 'quote_Quotes',
    ),
    'valid_until_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'valid_until_c',
      'vname' => 'LBL_VALID_UNTIL',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'quote_Quotesvalid_until_c',
      'custom_module' => 'quote_Quotes',
    ),
  ),
  'relationships' => 
  array (
    'quote_quotes_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Quotes',
      'rhs_table' => 'quote_quotes',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'quote_quotes_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Quotes',
      'rhs_table' => 'quote_quotes',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'quote_quotes_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Quotes',
      'rhs_table' => 'quote_quotes',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'quote_quotespk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
    'number' => 
    array (
      'name' => 'quote_quotesnumk',
      'type' => 'unique',
      'fields' => 
      array (
        0 => 'quote_quotes_number',
      ),
    ),
  ),
  'templates' => 
  array (
    'issue' => 'issue',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);