<?php 
 $GLOBALS["dictionary"]["EvMgr_EvParts"]=array (
  'table' => 'evmgr_evparts',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => false,
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'attendee_status' => 
    array (
      'required' => false,
      'name' => 'attendee_status',
      'vname' => 'LBL_ATTENDEE_STATUS',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => 'Invited',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_attendee_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'event_ce_hours' => 
    array (
      'required' => false,
      'name' => 'event_ce_hours',
      'vname' => 'LBL_EVENT_CE_HOURS',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_event_ce_hours_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'event_start_date_imported' => 
    array (
      'name' => 'event_start_date_imported',
      'type' => 'datetime',
      'vname' => 'LBL_EVENT_START_DATE_IMPORTED',
      'source' => 'non-db',
      'dbType' => 'non-db',
      'studio' => 'visible',
    ),
    'evmgr_evparts_contacts' => 
    array (
      'name' => 'evmgr_evparts_contacts',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_contacts',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'vname' => 'LBL_EVMGR_EVPARTS_CONTACTS_FROM_CONTACTS_TITLE',
      'id_name' => 'evmgr_evparts_contactscontacts_ida',
    ),
    'evmgr_evparts_contacts_name' => 
    array (
      'name' => 'evmgr_evparts_contacts_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_EVMGR_EVPARTS_CONTACTS_FROM_CONTACTS_TITLE',
      'save' => true,
      'id_name' => 'evmgr_evparts_contactscontacts_ida',
      'link' => 'evmgr_evparts_contacts',
      'table' => 'contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'db_concat_fields' => 
      array (
        0 => 'first_name',
        1 => 'last_name',
        'required' => true,
        'massupdate' => false,
      ),
    ),
    'evmgr_evparts_contactscontacts_ida' => 
    array (
      'name' => 'evmgr_evparts_contactscontacts_ida',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_contacts',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_EVMGR_EVPARTS_CONTACTS_FROM_EVMGR_EVPARTS_TITLE',
    ),
    'evmgr_evparts_evmgr_evs' => 
    array (
      'name' => 'evmgr_evparts_evmgr_evs',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_evmgr_evs',
      'source' => 'non-db',
      'module' => 'EvMgr_Evs',
      'bean_name' => 'EvMgr_Evs',
      'vname' => 'LBL_EVMGR_EVPARTS_EVMGR_EVS_FROM_EVMGR_EVS_TITLE',
      'id_name' => 'evmgr_evparts_evmgr_evsevmgr_evs_ida',
    ),
    'evmgr_evparts_evmgr_evs_name' => 
    array (
      'name' => 'evmgr_evparts_evmgr_evs_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_EVMGR_EVPARTS_EVMGR_EVS_FROM_EVMGR_EVS_TITLE',
      'save' => true,
      'id_name' => 'evmgr_evparts_evmgr_evsevmgr_evs_ida',
      'link' => 'evmgr_evparts_evmgr_evs',
      'table' => 'evmgr_evs',
      'module' => 'EvMgr_Evs',
      'rname' => 'name',
      'required' => true,
      'massupdate' => false,
    ),
    'evmgr_evparts_evmgr_evsevmgr_evs_ida' => 
    array (
      'name' => 'evmgr_evparts_evmgr_evsevmgr_evs_ida',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_evmgr_evs',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_EVMGR_EVPARTS_EVMGR_EVS_FROM_EVMGR_EVPARTS_TITLE',
    ),
  ),
  'relationships' => 
  array (
    'evmgr_evparts_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'EvMgr_EvParts',
      'rhs_table' => 'evmgr_evparts',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'evmgr_evparts_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'EvMgr_EvParts',
      'rhs_table' => 'evmgr_evparts',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'evmgr_evparts_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'EvMgr_EvParts',
      'rhs_table' => 'evmgr_evparts',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'evmgr_evpartspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => false,
);