<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN EvMgr_Evs
 */


class EvMgr_Evs_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'EvMgr_Evs';
	var $object_name = 'EvMgr_Evs';
	var $table_name = 'evmgr_evs';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $event_type;
		var $event_status;
		var $pre_material_required;
		var $accomodations_required;
		var $fire_alarm_schedule_checked;
		var $post_event_commentary;
		var $start_date;
		var $end_date;
		var $ce_hours_credit;
		var $num_invited;
		var $num_confirmed;
		var $num_nevershowed;
		var $num_participated;
		var $num_graduated;
		var $customer_contract;
		var $facilitator_contract;
		var $venue_contract;
		var $caterer_contract;
		var $accommodations_contract;
		var $program_designed;
		var $insurance_certificate_obtained;
		var $material_produced;
		var $marketing_started;
		var $travel_and_accom;
		var $pre_event_mailing_sent;
		var $attendee_status_updated;
		var $eval_scores_reported;
		var $budget_total;
		var $currency_id;
		var $budget_facilitator;
		var $budget_venue;
		var $budget_caterer;
		var $budget_material;
		var $budget_other;
		var $facilitator_fees;
		var $actual_cost_total;
		var $actual_cost_facilitator;
		var $actual_cost_venue;
		var $actual_cost_caterer;
		var $actual_cost_material;
		var $actual_cost_other;
		var $post_event_mailing_sent;
		function EvMgr_Evs_sugar(){	
		parent::Basic();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>