<?php 
 $GLOBALS["dictionary"]["simpl_Feed_Back_Form"]=array (
  'table' => 'simpl_feed_back_form',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'enabled',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
      'comments' => 'Date record created',
      'merge_filter' => 'disabled',
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
      'inline_edit' => true,
      'comments' => 'Full text of the note',
      'merge_filter' => 'disabled',
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'simpl_feed_back_form_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'simpl_feed_back_form_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'simpl_feed_back_form_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'opportunities_simpl_feed_back_form_1' => 
    array (
      'name' => 'opportunities_simpl_feed_back_form_1',
      'type' => 'link',
      'relationship' => 'opportunities_simpl_feed_back_form_1',
      'source' => 'non-db',
      'module' => 'Opportunities',
      'bean_name' => 'Opportunity',
      'vname' => 'LBL_OPPORTUNITIES_SIMPL_FEED_BACK_FORM_1_FROM_OPPORTUNITIES_TITLE',
      'id_name' => 'opportunities_simpl_feed_back_form_1opportunities_ida',
    ),
    'opportunities_simpl_feed_back_form_1_name' => 
    array (
      'name' => 'opportunities_simpl_feed_back_form_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_OPPORTUNITIES_SIMPL_FEED_BACK_FORM_1_FROM_OPPORTUNITIES_TITLE',
      'save' => true,
      'id_name' => 'opportunities_simpl_feed_back_form_1opportunities_ida',
      'link' => 'opportunities_simpl_feed_back_form_1',
      'table' => 'opportunities',
      'module' => 'Opportunities',
      'rname' => 'name',
    ),
    'opportunities_simpl_feed_back_form_1opportunities_ida' => 
    array (
      'name' => 'opportunities_simpl_feed_back_form_1opportunities_ida',
      'type' => 'link',
      'relationship' => 'opportunities_simpl_feed_back_form_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_OPPORTUNITIES_SIMPL_FEED_BACK_FORM_1_FROM_SIMPL_FEED_BACK_FORM_TITLE',
    ),
    'q2_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'What made you select Square Foot?',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q2_c',
      'vname' => 'LBL_Q2',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '3',
      'cols' => '35',
      'id' => 'simpl_Feed_Back_Formq2_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'q6_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Will you recommend us?',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q6_c',
      'vname' => 'LBL_Q6',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'simpl_Feed_Back_Formq6_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'q4_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Were you satisfied with the range of products we had to offer?',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q4_c',
      'vname' => 'LBL_Q4',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'simpl_Feed_Back_Formq4_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'q1_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'How did you hear about us? ',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q1_c',
      'vname' => 'LBL_Q1',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '3',
      'cols' => '35',
      'id' => 'simpl_Feed_Back_Formq1_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'q5_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'How would you rate the installation work done by us?',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q5_c',
      'vname' => 'LBL_Q5',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'simpl_Feed_Back_Formq5_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'q7_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'May we publish your opinion?',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q7_c',
      'vname' => 'LBL_Q7',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'simpl_Feed_Back_Formq7_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'q3_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Were the sales personnel helpful in choosing the right product for you?',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'q3_c',
      'vname' => 'LBL_Q3',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'simpl_Feed_Back_Formq3_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
    'date_entered_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Date Entered',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'date_entered_c',
      'vname' => 'LBL_DATE_ENTERED_C',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'simpl_Feed_Back_Formdate_entered_c',
      'custom_module' => 'simpl_Feed_Back_Form',
    ),
  ),
  'relationships' => 
  array (
    'simpl_feed_back_form_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'simpl_Feed_Back_Form',
      'rhs_table' => 'simpl_feed_back_form',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'simpl_feed_back_form_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'simpl_Feed_Back_Form',
      'rhs_table' => 'simpl_feed_back_form',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'simpl_feed_back_form_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'simpl_Feed_Back_Form',
      'rhs_table' => 'simpl_feed_back_form',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'simpl_feed_back_formpk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);