<?php 
 $GLOBALS["dictionary"]["Account"]=array (
  'table' => 'accounts',
  'audited' => true,
  'unified_search' => true,
  'full_text_search' => true,
  'unified_search_default_enabled' => true,
  'duplicate_merge' => true,
  'comment' => 'Accounts are organizations or entities that are the target of selling, support, and marketing activities, or have already purchased products or services',
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'type' => 'name',
      'dbType' => 'varchar',
      'vname' => 'LBL_NAME',
      'len' => 150,
      'comment' => 'Name of the Company',
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'audited' => true,
      'required' => true,
      'importable' => 'required',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'accounts_created_by',
      'vname' => 'LBL_CREATED_BY_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'accounts_modified_user',
      'vname' => 'LBL_MODIFIED_BY_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'accounts_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_accounts',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'account_type' => 
    array (
      'name' => 'account_type',
      'vname' => 'LBL_TYPE',
      'type' => 'enum',
      'options' => 'customer_type_list',
      'len' => 100,
      'comment' => 'The Company is of this type',
      'comments' => 'The Company is of this type',
      'merge_filter' => 'disabled',
    ),
    'industry' => 
    array (
      'name' => 'industry',
      'vname' => 'LBL_INDUSTRY',
      'type' => 'enum',
      'options' => 'industry_dom',
      'len' => 50,
      'comment' => 'The company belongs in this industry',
      'merge_filter' => 'enabled',
    ),
    'annual_revenue' => 
    array (
      'name' => 'annual_revenue',
      'vname' => 'LBL_ANNUAL_REVENUE',
      'type' => 'varchar',
      'len' => 100,
      'comment' => 'Annual revenue for this company',
      'merge_filter' => 'enabled',
    ),
    'phone_fax' => 
    array (
      'name' => 'phone_fax',
      'vname' => 'LBL_FAX',
      'type' => 'phone',
      'dbType' => 'varchar',
      'len' => 100,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 1,
      ),
      'comment' => 'The fax phone number of this company',
    ),
    'billing_address_street' => 
    array (
      'name' => 'billing_address_street',
      'vname' => 'LBL_BILLING_ADDRESS_STREET',
      'type' => 'varchar',
      'len' => '150',
      'comment' => 'The street address used for billing address',
      'group' => 'billing_address',
      'merge_filter' => 'disabled',
      'required' => true,
      'comments' => 'The street address used for billing address',
    ),
    'billing_address_street_2' => 
    array (
      'name' => 'billing_address_street_2',
      'vname' => 'LBL_BILLING_ADDRESS_STREET_2',
      'type' => 'varchar',
      'len' => '150',
      'source' => 'non-db',
    ),
    'billing_address_street_3' => 
    array (
      'name' => 'billing_address_street_3',
      'vname' => 'LBL_BILLING_ADDRESS_STREET_3',
      'type' => 'varchar',
      'len' => '150',
      'source' => 'non-db',
    ),
    'billing_address_street_4' => 
    array (
      'name' => 'billing_address_street_4',
      'vname' => 'LBL_BILLING_ADDRESS_STREET_4',
      'type' => 'varchar',
      'len' => '150',
      'source' => 'non-db',
    ),
    'billing_address_city' => 
    array (
      'name' => 'billing_address_city',
      'vname' => 'LBL_BILLING_ADDRESS_CITY',
      'type' => 'varchar',
      'len' => '100',
      'comment' => 'The city used for billing address',
      'group' => 'billing_address',
      'merge_filter' => 'disabled',
      'required' => true,
      'comments' => 'The city used for billing address',
    ),
    'billing_address_state' => 
    array (
      'name' => 'billing_address_state',
      'vname' => 'LBL_BILLING_ADDRESS_STATE',
      'type' => 'varchar',
      'len' => '100',
      'group' => 'billing_address',
      'comment' => 'The state used for billing address',
      'merge_filter' => 'disabled',
      'required' => true,
      'comments' => 'The state used for billing address',
    ),
    'billing_address_postalcode' => 
    array (
      'name' => 'billing_address_postalcode',
      'vname' => 'LBL_BILLING_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'len' => '20',
      'group' => 'billing_address',
      'comment' => 'The postal code used for billing address',
      'merge_filter' => 'disabled',
      'required' => true,
      'comments' => 'The postal code used for billing address',
    ),
    'billing_address_country' => 
    array (
      'name' => 'billing_address_country',
      'vname' => 'LBL_BILLING_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'group' => 'billing_address',
      'comment' => 'The country used for the billing address',
      'merge_filter' => 'disabled',
      'required' => true,
      'comments' => 'The country used for the billing address',
      'default' => 'India',
      'inline_edit' => true,
    ),
    'rating' => 
    array (
      'name' => 'rating',
      'vname' => 'LBL_RATING',
      'type' => 'varchar',
      'len' => 100,
      'comment' => 'An arbitrary rating for this company for use in comparisons with others',
    ),
    'phone_office' => 
    array (
      'name' => 'phone_office',
      'vname' => 'LBL_PHONE_OFFICE',
      'type' => 'phone',
      'dbType' => 'varchar',
      'len' => 100,
      'audited' => true,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 1,
      ),
      'comment' => 'The office phone number',
      'merge_filter' => 'disabled',
      'required' => true,
      'comments' => 'The office phone number',
    ),
    'phone_alternate' => 
    array (
      'name' => 'phone_alternate',
      'vname' => 'LBL_PHONE_ALT',
      'type' => 'phone',
      'group' => 'phone_office',
      'dbType' => 'varchar',
      'len' => 100,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 1,
      ),
      'comment' => 'An alternate phone number',
      'merge_filter' => 'enabled',
    ),
    'website' => 
    array (
      'name' => 'website',
      'vname' => 'LBL_WEBSITE',
      'type' => 'url',
      'dbType' => 'varchar',
      'len' => 255,
      'comment' => 'URL of website for the company',
    ),
    'ownership' => 
    array (
      'name' => 'ownership',
      'vname' => 'LBL_OWNERSHIP',
      'type' => 'varchar',
      'len' => 100,
      'comment' => '',
    ),
    'employees' => 
    array (
      'name' => 'employees',
      'vname' => 'LBL_EMPLOYEES',
      'type' => 'varchar',
      'len' => 10,
      'comment' => 'Number of employees, varchar to accomodate for both number (100) or range (50-100)',
    ),
    'ticker_symbol' => 
    array (
      'name' => 'ticker_symbol',
      'vname' => 'LBL_TICKER_SYMBOL',
      'type' => 'varchar',
      'len' => 10,
      'comment' => 'The stock trading (ticker) symbol for the company',
      'merge_filter' => 'enabled',
    ),
    'shipping_address_street' => 
    array (
      'name' => 'shipping_address_street',
      'vname' => 'LBL_SHIPPING_ADDRESS_STREET',
      'type' => 'varchar',
      'len' => 150,
      'group' => 'shipping_address',
      'comment' => 'The street address used for for shipping purposes',
      'merge_filter' => 'enabled',
    ),
    'shipping_address_street_2' => 
    array (
      'name' => 'shipping_address_street_2',
      'vname' => 'LBL_SHIPPING_ADDRESS_STREET_2',
      'type' => 'varchar',
      'len' => 150,
      'source' => 'non-db',
    ),
    'shipping_address_street_3' => 
    array (
      'name' => 'shipping_address_street_3',
      'vname' => 'LBL_SHIPPING_ADDRESS_STREET_3',
      'type' => 'varchar',
      'len' => 150,
      'source' => 'non-db',
    ),
    'shipping_address_street_4' => 
    array (
      'name' => 'shipping_address_street_4',
      'vname' => 'LBL_SHIPPING_ADDRESS_STREET_4',
      'type' => 'varchar',
      'len' => 150,
      'source' => 'non-db',
    ),
    'shipping_address_city' => 
    array (
      'name' => 'shipping_address_city',
      'vname' => 'LBL_SHIPPING_ADDRESS_CITY',
      'type' => 'varchar',
      'len' => 100,
      'group' => 'shipping_address',
      'comment' => 'The city used for the shipping address',
      'merge_filter' => 'enabled',
    ),
    'shipping_address_state' => 
    array (
      'name' => 'shipping_address_state',
      'vname' => 'LBL_SHIPPING_ADDRESS_STATE',
      'type' => 'varchar',
      'len' => 100,
      'group' => 'shipping_address',
      'comment' => 'The state used for the shipping address',
      'merge_filter' => 'enabled',
    ),
    'shipping_address_postalcode' => 
    array (
      'name' => 'shipping_address_postalcode',
      'vname' => 'LBL_SHIPPING_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'len' => 20,
      'group' => 'shipping_address',
      'comment' => 'The zip code used for the shipping address',
      'merge_filter' => 'enabled',
    ),
    'shipping_address_country' => 
    array (
      'name' => 'shipping_address_country',
      'vname' => 'LBL_SHIPPING_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'group' => 'shipping_address',
      'comment' => 'The country used for the shipping address',
      'merge_filter' => 'enabled',
    ),
    'email1' => 
    array (
      'name' => 'email1',
      'vname' => 'LBL_EMAIL',
      'group' => 'email1',
      'type' => 'varchar',
      'function' => 
      array (
        'name' => 'getEmailAddressWidget',
        'returns' => 'html',
      ),
      'source' => 'non-db',
      'studio' => 
      array (
        'editField' => true,
        'searchview' => false,
      ),
      'full_text_search' => 
      array (
        'boost' => 3,
        'analyzer' => 'whitespace',
      ),
      'required' => true,
      'merge_filter' => 'disabled',
    ),
    'email_addresses_primary' => 
    array (
      'name' => 'email_addresses_primary',
      'type' => 'link',
      'relationship' => 'accounts_email_addresses_primary',
      'source' => 'non-db',
      'vname' => 'LBL_EMAIL_ADDRESS_PRIMARY',
      'duplicate_merge' => 'disabled',
      'studio' => 
      array (
        'formula' => false,
      ),
    ),
    'email_addresses' => 
    array (
      'name' => 'email_addresses',
      'type' => 'link',
      'relationship' => 'accounts_email_addresses',
      'source' => 'non-db',
      'vname' => 'LBL_EMAIL_ADDRESSES',
      'reportable' => false,
      'unified_search' => true,
      'rel_fields' => 
      array (
        'primary_address' => 
        array (
          'type' => 'bool',
        ),
      ),
      'studio' => 
      array (
        'formula' => false,
      ),
    ),
    'email_addresses_non_primary' => 
    array (
      'name' => 'email_addresses_non_primary',
      'type' => 'email',
      'source' => 'non-db',
      'vname' => 'LBL_EMAIL_NON_PRIMARY',
      'studio' => false,
      'reportable' => false,
      'massupdate' => false,
    ),
    'parent_id' => 
    array (
      'name' => 'parent_id',
      'vname' => 'LBL_PARENT_ACCOUNT_ID',
      'type' => 'id',
      'required' => false,
      'reportable' => false,
      'audited' => true,
      'comment' => 'Account ID of the parent of this account',
    ),
    'sic_code' => 
    array (
      'name' => 'sic_code',
      'vname' => 'LBL_SIC_CODE',
      'type' => 'varchar',
      'len' => 10,
      'comment' => 'SIC code of the account',
    ),
    'parent_name' => 
    array (
      'name' => 'parent_name',
      'rname' => 'name',
      'id_name' => 'parent_id',
      'vname' => 'LBL_MEMBER_OF',
      'type' => 'relate',
      'isnull' => 'true',
      'module' => 'Accounts',
      'table' => 'accounts',
      'massupdate' => false,
      'source' => 'non-db',
      'len' => 36,
      'link' => 'member_of',
      'unified_search' => true,
      'importable' => 'true',
    ),
    'members' => 
    array (
      'name' => 'members',
      'type' => 'link',
      'relationship' => 'member_accounts',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'source' => 'non-db',
      'vname' => 'LBL_MEMBERS',
    ),
    'member_of' => 
    array (
      'name' => 'member_of',
      'type' => 'link',
      'relationship' => 'member_accounts',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'link_type' => 'one',
      'source' => 'non-db',
      'vname' => 'LBL_MEMBER_OF',
      'side' => 'right',
    ),
    'email_opt_out' => 
    array (
      'name' => 'email_opt_out',
      'vname' => 'LBL_EMAIL_OPT_OUT',
      'source' => 'non-db',
      'type' => 'bool',
      'massupdate' => false,
      'studio' => 'false',
    ),
    'invalid_email' => 
    array (
      'name' => 'invalid_email',
      'vname' => 'LBL_INVALID_EMAIL',
      'source' => 'non-db',
      'type' => 'bool',
      'massupdate' => false,
      'studio' => 'false',
    ),
    'cases' => 
    array (
      'name' => 'cases',
      'type' => 'link',
      'relationship' => 'account_cases',
      'module' => 'Cases',
      'bean_name' => 'aCase',
      'source' => 'non-db',
      'vname' => 'LBL_CASES',
    ),
    'email' => 
    array (
      'name' => 'email',
      'type' => 'email',
      'query_type' => 'default',
      'source' => 'non-db',
      'operator' => 'subquery',
      'subquery' => 'SELECT eabr.bean_id FROM email_addr_bean_rel eabr JOIN email_addresses ea ON (ea.id = eabr.email_address_id) WHERE eabr.deleted=0 AND ea.email_address LIKE',
      'db_field' => 
      array (
        0 => 'id',
      ),
      'vname' => 'LBL_ANY_EMAIL',
      'studio' => 
      array (
        'visible' => false,
        'searchview' => true,
      ),
      'importable' => false,
    ),
    'tasks' => 
    array (
      'name' => 'tasks',
      'type' => 'link',
      'relationship' => 'account_tasks',
      'module' => 'Tasks',
      'bean_name' => 'Task',
      'source' => 'non-db',
      'vname' => 'LBL_TASKS',
    ),
    'notes' => 
    array (
      'name' => 'notes',
      'type' => 'link',
      'relationship' => 'account_notes',
      'module' => 'Notes',
      'bean_name' => 'Note',
      'source' => 'non-db',
      'vname' => 'LBL_NOTES',
    ),
    'meetings' => 
    array (
      'name' => 'meetings',
      'type' => 'link',
      'relationship' => 'account_meetings',
      'module' => 'Meetings',
      'bean_name' => 'Meeting',
      'source' => 'non-db',
      'vname' => 'LBL_MEETINGS',
    ),
    'calls' => 
    array (
      'name' => 'calls',
      'type' => 'link',
      'relationship' => 'account_calls',
      'module' => 'Calls',
      'bean_name' => 'Call',
      'source' => 'non-db',
      'vname' => 'LBL_CALLS',
    ),
    'emails' => 
    array (
      'name' => 'emails',
      'type' => 'link',
      'relationship' => 'emails_accounts_rel',
      'module' => 'Emails',
      'bean_name' => 'Email',
      'source' => 'non-db',
      'vname' => 'LBL_EMAILS',
      'studio' => 
      array (
        'formula' => false,
      ),
    ),
    'documents' => 
    array (
      'name' => 'documents',
      'type' => 'link',
      'relationship' => 'documents_accounts',
      'source' => 'non-db',
      'vname' => 'LBL_DOCUMENTS_SUBPANEL_TITLE',
    ),
    'bugs' => 
    array (
      'name' => 'bugs',
      'type' => 'link',
      'relationship' => 'accounts_bugs',
      'module' => 'Bugs',
      'bean_name' => 'Bug',
      'source' => 'non-db',
      'vname' => 'LBL_BUGS',
    ),
    'contacts' => 
    array (
      'name' => 'contacts',
      'type' => 'link',
      'relationship' => 'accounts_contacts',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'source' => 'non-db',
      'vname' => 'LBL_CONTACTS',
    ),
    'opportunities' => 
    array (
      'name' => 'opportunities',
      'type' => 'link',
      'relationship' => 'accounts_opportunities',
      'module' => 'Opportunities',
      'bean_name' => 'Opportunity',
      'source' => 'non-db',
      'vname' => 'LBL_OPPORTUNITY',
    ),
    'project' => 
    array (
      'name' => 'project',
      'type' => 'link',
      'relationship' => 'projects_accounts',
      'module' => 'Project',
      'bean_name' => 'Project',
      'source' => 'non-db',
      'vname' => 'LBL_PROJECTS',
    ),
    'leads' => 
    array (
      'name' => 'leads',
      'type' => 'link',
      'relationship' => 'account_leads',
      'module' => 'Leads',
      'bean_name' => 'Lead',
      'source' => 'non-db',
      'vname' => 'LBL_LEADS',
    ),
    'campaigns' => 
    array (
      'name' => 'campaigns',
      'type' => 'link',
      'relationship' => 'account_campaign_log',
      'module' => 'CampaignLog',
      'bean_name' => 'CampaignLog',
      'source' => 'non-db',
      'vname' => 'LBL_CAMPAIGNLOG',
      'studio' => 
      array (
        'formula' => false,
      ),
    ),
    'campaign_accounts' => 
    array (
      'name' => 'campaign_accounts',
      'type' => 'link',
      'vname' => 'LBL_CAMPAIGNS',
      'relationship' => 'campaign_accounts',
      'source' => 'non-db',
    ),
    'campaign_id' => 
    array (
      'name' => 'campaign_id',
      'comment' => 'Campaign that generated Account',
      'vname' => 'LBL_CAMPAIGN_ID',
      'rname' => 'id',
      'id_name' => 'campaign_id',
      'type' => 'id',
      'table' => 'campaigns',
      'isnull' => 'true',
      'module' => 'Campaigns',
      'reportable' => false,
      'massupdate' => false,
      'duplicate_merge' => 'disabled',
    ),
    'campaign_name' => 
    array (
      'name' => 'campaign_name',
      'rname' => 'name',
      'vname' => 'LBL_CAMPAIGN',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'campaigns',
      'id_name' => 'campaign_id',
      'link' => 'campaign_accounts',
      'module' => 'Campaigns',
      'duplicate_merge' => 'disabled',
      'comment' => 'The first campaign name for Account (Meta-data only)',
    ),
    'prospect_lists' => 
    array (
      'name' => 'prospect_lists',
      'type' => 'link',
      'relationship' => 'prospect_list_accounts',
      'module' => 'ProspectLists',
      'source' => 'non-db',
      'vname' => 'LBL_PROSPECT_LIST',
    ),
    'aos_quotes' => 
    array (
      'name' => 'aos_quotes',
      'vname' => 'LBL_AOS_QUOTES',
      'type' => 'link',
      'relationship' => 'account_aos_quotes',
      'module' => 'AOS_Quotes',
      'bean_name' => 'AOS_Quotes',
      'source' => 'non-db',
    ),
    'aos_invoices' => 
    array (
      'name' => 'aos_invoices',
      'vname' => 'LBL_AOS_INVOICES',
      'type' => 'link',
      'relationship' => 'account_aos_invoices',
      'module' => 'AOS_Invoices',
      'bean_name' => 'AOS_Invoices',
      'source' => 'non-db',
    ),
    'aos_contracts' => 
    array (
      'name' => 'aos_contracts',
      'vname' => 'LBL_AOS_CONTRACTS',
      'type' => 'link',
      'relationship' => 'account_aos_contracts',
      'module' => 'AOS_Contracts',
      'bean_name' => 'AOS_Contracts',
      'source' => 'non-db',
    ),
    'flip_charts_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'flip_charts_c',
      'vname' => 'LBL_FLIP_CHARTS',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsflip_charts_c',
      'custom_module' => 'Accounts',
    ),
    'consult_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'consult_c',
      'vname' => 'LBL_CONSULT',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsconsult_c',
      'custom_module' => 'Accounts',
    ),
    'reference2_comments_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'reference2_comments_c',
      'vname' => 'LBL_REFERENCE2_COMMENTS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreference2_comments_c',
      'custom_module' => 'Accounts',
    ),
    'corporate_rate_value_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'corporate_rate_value_c',
      'vname' => 'LBL_CORPORATE_RATE_VALUE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountscorporate_rate_value_c',
      'custom_module' => 'Accounts',
    ),
    'consult_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'consult_fees_c',
      'vname' => 'LBL_CONSULT_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsconsult_fees_c',
      'custom_module' => 'Accounts',
    ),
    'travel_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'travel_fees_c',
      'vname' => 'LBL_TRAVEL_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountstravel_fees_c',
      'custom_module' => 'Accounts',
    ),
    'fac_rent_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'fac_rent_fees_c',
      'vname' => 'LBL_FAC_RENT_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsfac_rent_fees_c',
      'custom_module' => 'Accounts',
    ),
    'quote_quotes_accounts' => 
    array (
      'name' => 'quote_quotes_accounts',
      'type' => 'link',
      'relationship' => 'quote_quotes_accounts',
      'source' => 'non-db',
      'module' => 'quote_Quotes',
      'bean_name' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTES_ACCOUNTS_FROM_QUOTE_QUOTES_TITLE',
    ),
    'contractor_c' => 
    array (
      'labelValue' => 'Contractor',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contractor_c',
      'vname' => 'LBL_CONTRACTOR',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountscontractor_c',
      'custom_module' => 'Accounts',
    ),
    'reference3_comments_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'reference3_comments_c',
      'vname' => 'LBL_REFERENCE3_COMMENTS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreference3_comments_c',
      'custom_module' => 'Accounts',
    ),
    'other_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'other_fees_c',
      'vname' => 'LBL_OTHER_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsother_fees_c',
      'custom_module' => 'Accounts',
    ),
    'internet_avail_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'internet_avail_c',
      'vname' => 'LBL_INTERNET_AVAIL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsinternet_avail_c',
      'custom_module' => 'Accounts',
    ),
    'reference3_c' => 
    array (
      'name' => 'reference3_c',
      'label' => 'LBL_REFERENCE3',
      'type' => 'relate',
      'default_value' => false,
      'comments' => '',
      'help' => '',
      'massupdate' => false,
      'required' => false,
      'reportable' => true,
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'studio' => 'visible',
      'audited' => false,
      'max_size' => '255',
      'ext1' => '',
      'ext3' => '',
      'calculated' => false,
      'source' => 'non-db',
      'id_name' => 'contact_id3_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
    ),
    'others_c' => 
    array (
      'labelValue' => 'Others',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'others_c',
      'vname' => 'LBL_OTHERS',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsothers_c',
      'custom_module' => 'Accounts',
    ),
    'reqd_deposit_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'reqd_deposit_c',
      'vname' => 'LBL_REQD_DEPOSIT',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreqd_deposit_c',
      'custom_module' => 'Accounts',
    ),
    'contact_id4_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contact_id4_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'Accountscontact_id4_c',
      'custom_module' => 'Accounts',
    ),
    'num_guest_rooms_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'num_guest_rooms_c',
      'vname' => 'LBL_NUM_GUEST_ROOMS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsnum_guest_rooms_c',
      'custom_module' => 'Accounts',
    ),
    'cat_contract_status_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'cat_contract_status_c',
      'vname' => 'LBL_CAT_CONTRACT_STATUS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'NA',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountscat_contract_status_c',
      'custom_module' => 'Accounts',
    ),
    'parking_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'parking_fees_c',
      'vname' => 'LBL_PARKING_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsparking_fees_c',
      'custom_module' => 'Accounts',
    ),
    'accounts_contacts_99' => 
    array (
      'name' => 'accounts_contacts_99',
      'type' => 'link',
      'relationship' => 'accounts_contacts_99',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => false,
      'vname' => 'LBL_ACCOUNTS_CONTACTS_99_FROM_CONTACTS_TITLE',
    ),
    'sports_c' => 
    array (
      'labelValue' => 'Sports',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'sports_c',
      'vname' => 'LBL_SPORTS',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountssports_c',
      'custom_module' => 'Accounts',
    ),
    'customer_id_c' => 
    array (
      'labelValue' => 'Customer Id',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'customer_id_c',
      'vname' => 'LBL_CUSTOMER_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountscustomer_id_c',
      'custom_module' => 'Accounts',
    ),
    'caterer_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'caterer_fees_c',
      'vname' => 'LBL_CATERER_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountscaterer_fees_c',
      'custom_module' => 'Accounts',
    ),
    'av_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'av_fees_c',
      'vname' => 'LBL_AV_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsav_fees_c',
      'custom_module' => 'Accounts',
    ),
    'fac_rating_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'fac_rating_c',
      'vname' => 'LBL_FAC_RATING',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Med',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_hi_med_lo_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountsfac_rating_c',
      'custom_module' => 'Accounts',
    ),
    'stages_allowed_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'stages_allowed_c',
      'vname' => 'LBL_STAGES_ALLOWED',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsstages_allowed_c',
      'custom_module' => 'Accounts',
    ),
    'regn_area_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'regn_area_c',
      'vname' => 'LBL_REGN_AREA',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsregn_area_c',
      'custom_module' => 'Accounts',
    ),
    'accounts_quote_quote_1' => 
    array (
      'name' => 'accounts_quote_quote_1',
      'type' => 'link',
      'relationship' => 'accounts_quote_quote_1',
      'source' => 'non-db',
      'module' => 'quote_Quote',
      'bean_name' => 'quote_Quote',
      'side' => 'right',
      'vname' => 'LBL_ACCOUNTS_QUOTE_QUOTE_1_FROM_QUOTE_QUOTE_TITLE',
    ),
    'theatre_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'theatre_c',
      'vname' => 'LBL_THEATRE',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountstheatre_c',
      'custom_module' => 'Accounts',
    ),
    'facilitate_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'facilitate_fees_c',
      'vname' => 'LBL_FACILITATE_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsfacilitate_fees_c',
      'custom_module' => 'Accounts',
    ),
    'reference2_c' => 
    array (
      'name' => 'reference2_c',
      'label' => 'LBL_REFERENCE2',
      'type' => 'relate',
      'default_value' => false,
      'comments' => '',
      'help' => '',
      'massupdate' => false,
      'required' => false,
      'reportable' => true,
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'studio' => 'visible',
      'audited' => false,
      'max_size' => '255',
      'ext1' => '',
      'ext3' => '',
      'calculated' => false,
      'source' => 'non-db',
      'id_name' => 'contact_id2_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
    ),
    'accounts_accounts_99' => 
    array (
      'name' => 'accounts_accounts_99',
      'type' => 'link',
      'relationship' => 'accounts_accounts_99',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => false,
      'vname' => 'LBL_ACCOUNTS_ACCOUNTS_99_FROM_ACCOUNTS_R_TITLE',
    ),
    'hospital_c' => 
    array (
      'labelValue' => 'Hospital',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'hospital_c',
      'vname' => 'LBL_HOSPITAL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountshospital_c',
      'custom_module' => 'Accounts',
    ),
    'evmgr_evs_accounts' => 
    array (
      'name' => 'evmgr_evs_accounts',
      'type' => 'link',
      'relationship' => 'evmgr_evs_accounts',
      'source' => 'non-db',
      'module' => 'EvMgr_Evs',
      'bean_name' => 'EvMgr_Evs',
      'vname' => 'LBL_EVMGR_EVS_ACCOUNTS_FROM_EVMGR_EVS_TITLE',
    ),
    'builder_c' => 
    array (
      'labelValue' => 'Builder',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'builder_c',
      'vname' => 'LBL_BUILDER',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsbuilder_c',
      'custom_module' => 'Accounts',
    ),
    'meeting_rooms_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'meeting_rooms_c',
      'vname' => 'LBL_MEETING_ROOMS',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsmeeting_rooms_c',
      'custom_module' => 'Accounts',
    ),
    'deposit_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'deposit_fees_c',
      'vname' => 'LBL_DEPOSIT_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsdeposit_fees_c',
      'custom_module' => 'Accounts',
    ),
    'av_contact_c' => 
    array (
      'name' => 'av_contact_c',
      'label' => 'LBL_AV_CONTACT',
      'type' => 'relate',
      'default_value' => false,
      'comments' => '',
      'help' => '',
      'massupdate' => false,
      'required' => false,
      'reportable' => true,
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'studio' => 'visible',
      'audited' => false,
      'max_size' => '255',
      'ext1' => '',
      'ext3' => '',
      'calculated' => false,
      'source' => 'non-db',
      'id_name' => 'contact_id4_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
    ),
    'receiving_dock_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'receiving_dock_c',
      'vname' => 'LBL_RECEIVING_DOCK',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreceiving_dock_c',
      'custom_module' => 'Accounts',
    ),
    'educational_institution_c' => 
    array (
      'labelValue' => 'Educational Institution',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'educational_institution_c',
      'vname' => 'LBL_EDUCATIONAL_INSTITUTION',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountseducational_institution_c',
      'custom_module' => 'Accounts',
    ),
    'refund_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'refund_fees_c',
      'vname' => 'LBL_REFUND_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsrefund_fees_c',
      'custom_module' => 'Accounts',
    ),
    'venue_rating_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'venue_rating_c',
      'vname' => 'LBL_VENUE_RATING',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Med',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_hi_med_lo_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountsvenue_rating_c',
      'custom_module' => 'Accounts',
    ),
    'dining_room_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'dining_room_c',
      'vname' => 'LBL_DINING_ROOM',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsdining_room_c',
      'custom_module' => 'Accounts',
    ),
    'implement_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'implement_c',
      'vname' => 'LBL_IMPLEMENT',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsimplement_c',
      'custom_module' => 'Accounts',
    ),
    'food_specialty_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'food_specialty_c',
      'vname' => 'LBL_FOOD_SPECIALTY',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsfood_specialty_c',
      'custom_module' => 'Accounts',
    ),
    'venue_comments_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'venue_comments_c',
      'vname' => 'LBL_VENUE_COMMENTS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsvenue_comments_c',
      'custom_module' => 'Accounts',
    ),
    'reception_area_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'reception_area_c',
      'vname' => 'LBL_RECEPTION_AREA',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreception_area_c',
      'custom_module' => 'Accounts',
    ),
    'contact_id3_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contact_id3_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'Accountscontact_id3_c',
      'custom_module' => 'Accounts',
    ),
    'implement_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'implement_fees_c',
      'vname' => 'LBL_IMPLEMENT_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsimplement_fees_c',
      'custom_module' => 'Accounts',
    ),
    'reference1_comments_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'reference1_comments_c',
      'vname' => 'LBL_REFERENCE1_COMMENTS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreference1_comments_c',
      'custom_module' => 'Accounts',
    ),
    'ven_contract_status_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'ven_contract_status_c',
      'vname' => 'LBL_VEN_CONTRACT_STATUS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'NA',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountsven_contract_status_c',
      'custom_module' => 'Accounts',
    ),
    'fac_contract_status_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'fac_contract_status_c',
      'vname' => 'LBL_FAC_CONTRACT_STATUS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'NA',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountsfac_contract_status_c',
      'custom_module' => 'Accounts',
    ),
    'parking_avail_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'parking_avail_c',
      'vname' => 'LBL_PARKING_AVAIL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsparking_avail_c',
      'custom_module' => 'Accounts',
    ),
    'receiving_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'receiving_fees_c',
      'vname' => 'LBL_RECEIVING_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsreceiving_fees_c',
      'custom_module' => 'Accounts',
    ),
    'contact_id1_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contact_id1_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'Accountscontact_id1_c',
      'custom_module' => 'Accounts',
    ),
    'evmgr_pgms_accounts' => 
    array (
      'name' => 'evmgr_pgms_accounts',
      'type' => 'link',
      'relationship' => 'evmgr_pgms_accounts',
      'source' => 'non-db',
      'module' => 'EvMgr_Pgms',
      'bean_name' => 'EvMgr_Pgms',
      'side' => 'right',
      'vname' => 'LBL_EVMGR_PGMS_ACCOUNTS_FROM_EVMGR_PGMS_TITLE',
    ),
    'corporate_rate_avail_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'corporate_rate_avail_c',
      'vname' => 'LBL_CORPORATE_RATE_AVAIL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountscorporate_rate_avail_c',
      'custom_module' => 'Accounts',
    ),
    'reference1_c' => 
    array (
      'name' => 'reference1_c',
      'label' => 'LBL_REFERENCE1',
      'type' => 'relate',
      'default_value' => false,
      'comments' => '',
      'help' => '',
      'massupdate' => false,
      'required' => false,
      'reportable' => true,
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'studio' => 'visible',
      'audited' => false,
      'max_size' => '255',
      'ext1' => '',
      'ext3' => '',
      'calculated' => false,
      'source' => 'non-db',
      'id_name' => 'contact_id1_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
    ),
    'caterer_rating_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'caterer_rating_c',
      'vname' => 'LBL_CATERER_RATING',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Med',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_hi_med_lo_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountscaterer_rating_c',
      'custom_module' => 'Accounts',
    ),
    'contact_id2_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contact_id2_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'Accountscontact_id2_c',
      'custom_module' => 'Accounts',
    ),
    'customer_type_c' => 
    array (
      'labelValue' => 'Customer Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'customer_type_c',
      'vname' => 'LBL_CUSTOMER_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'customer_type_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountscustomer_type_c',
      'custom_module' => 'Accounts',
    ),
    'venue_restrictions_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'venue_restrictions_c',
      'vname' => 'LBL_VENUE_RESTRICTIONS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsvenue_restrictions_c',
      'custom_module' => 'Accounts',
    ),
    'evmgr_venrms_accounts' => 
    array (
      'name' => 'evmgr_venrms_accounts',
      'type' => 'link',
      'relationship' => 'evmgr_venrms_accounts',
      'source' => 'non-db',
      'module' => 'EvMgr_VenRms',
      'bean_name' => 'EvMgr_VenRms',
      'side' => 'right',
      'vname' => 'LBL_EVMGR_VENRMS_ACCOUNTS_FROM_EVMGR_VENRMS_TITLE',
    ),
    'quote_quote_accounts' => 
    array (
      'name' => 'quote_quote_accounts',
      'type' => 'link',
      'relationship' => 'quote_quote_accounts',
      'source' => 'non-db',
      'module' => 'quote_Quote',
      'bean_name' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_QUOTE_ACCOUNTS_FROM_QUOTE_QUOTE_TITLE',
    ),
    'travel_reimb_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'travel_reimb_c',
      'vname' => 'LBL_TRAVEL_REIMB',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountstravel_reimb_c',
      'custom_module' => 'Accounts',
    ),
    'exclusive_av_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'exclusive_av_c',
      'vname' => 'LBL_EXCLUSIVE_AV',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsexclusive_av_c',
      'custom_module' => 'Accounts',
    ),
    'exclusive_caterer_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'exclusive_caterer_c',
      'vname' => 'LBL_EXCLUSIVE_CATERER',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsexclusive_caterer_c',
      'custom_module' => 'Accounts',
    ),
    'own_facil_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'own_facil_c',
      'vname' => 'LBL_OWN_FACIL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsown_facil_c',
      'custom_module' => 'Accounts',
    ),
    'is_existing_customer_c' => 
    array (
      'labelValue' => 'Is Existing Customer',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'is_existing_customer_c',
      'vname' => 'LBL_IS_EXISTING_CUSTOMER',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsis_existing_customer_c',
      'custom_module' => 'Accounts',
    ),
    'hotel_c' => 
    array (
      'labelValue' => 'Hotel',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'hotel_c',
      'vname' => 'LBL_HOTEL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountshotel_c',
      'custom_module' => 'Accounts',
    ),
    'flip_chart_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'flip_chart_fees_c',
      'vname' => 'LBL_FLIP_CHART_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsflip_chart_fees_c',
      'custom_module' => 'Accounts',
    ),
    'pharmaceutical_c' => 
    array (
      'labelValue' => 'Pharmaceutical',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'pharmaceutical_c',
      'vname' => 'LBL_PHARMACEUTICAL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountspharmaceutical_c',
      'custom_module' => 'Accounts',
    ),
    'retail_c' => 
    array (
      'labelValue' => 'Retail',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'retail_c',
      'vname' => 'LBL_RETAIL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsretail_c',
      'custom_module' => 'Accounts',
    ),
    'will_book_block_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'will_book_block_c',
      'vname' => 'LBL_WILL_BOOK_BLOCK',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountswill_book_block_c',
      'custom_module' => 'Accounts',
    ),
    'internet_fees_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'internet_fees_c',
      'vname' => 'LBL_INTERNET_FEES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsinternet_fees_c',
      'custom_module' => 'Accounts',
    ),
    'caterer_restrictions_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'caterer_restrictions_c',
      'vname' => 'LBL_CATERER_RESTRICTIONS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountscaterer_restrictions_c',
      'custom_module' => 'Accounts',
    ),
    'venue_type_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'venue_type_c',
      'vname' => 'LBL_VENUE_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Hotel',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_venue_type_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'Accountsvenue_type_c',
      'custom_module' => 'Accounts',
    ),
    'av_avail_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'av_avail_c',
      'vname' => 'LBL_AV_AVAIL',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsav_avail_c',
      'custom_module' => 'Accounts',
    ),
    'facilitate_c' => 
    array (
      'duplicate_merge_dom_value' => 0,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'facilitate_c',
      'vname' => 'LBL_FACILITATE',
      'type' => 'bool',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsfacilitate_c',
      'custom_module' => 'Accounts',
    ),
    'jjwg_maps_address_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'jjwg_maps_address_c',
      'vname' => 'LBL_JJWG_MAPS_ADDRESS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => 'Address',
      'help' => 'Address',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsjjwg_maps_address_c',
      'custom_module' => 'Accounts',
    ),
    'jjwg_maps_geocode_status_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'jjwg_maps_geocode_status_c',
      'vname' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Accountsjjwg_maps_geocode_status_c',
      'custom_module' => 'Accounts',
    ),
    'jjwg_maps_lat_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'jjwg_maps_lat_c',
      'vname' => 'LBL_JJWG_MAPS_LAT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00000000',
      'no_default' => false,
      'comments' => '',
      'help' => 'Latitude',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '8',
      'id' => 'Accountsjjwg_maps_lat_c',
      'custom_module' => 'Accounts',
    ),
    'jjwg_maps_lng_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'jjwg_maps_lng_c',
      'vname' => 'LBL_JJWG_MAPS_LNG',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00000000',
      'no_default' => false,
      'comments' => '',
      'help' => 'Longitude',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '11',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '8',
      'id' => 'Accountsjjwg_maps_lng_c',
      'custom_module' => 'Accounts',
    ),
  ),
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'accountspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
    0 => 
    array (
      'name' => 'idx_accnt_id_del',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'id',
        1 => 'deleted',
      ),
    ),
    1 => 
    array (
      'name' => 'idx_accnt_name_del',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'name',
        1 => 'deleted',
      ),
    ),
    2 => 
    array (
      'name' => 'idx_accnt_assigned_del',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'deleted',
        1 => 'assigned_user_id',
      ),
    ),
    3 => 
    array (
      'name' => 'idx_accnt_parent_id',
      'type' => 'index',
      'fields' => 
      array (
        0 => 'parent_id',
      ),
    ),
  ),
  'relationships' => 
  array (
    'accounts_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'Accounts',
      'rhs_table' => 'accounts',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'accounts_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'Accounts',
      'rhs_table' => 'accounts',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'accounts_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'Accounts',
      'rhs_table' => 'accounts',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_accounts' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'Accounts',
      'rhs_table' => 'accounts',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'Accounts',
    ),
    'accounts_email_addresses' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'EmailAddresses',
      'rhs_table' => 'email_addresses',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'email_addr_bean_rel',
      'join_key_lhs' => 'bean_id',
      'join_key_rhs' => 'email_address_id',
      'relationship_role_column' => 'bean_module',
      'relationship_role_column_value' => 'Accounts',
    ),
    'accounts_email_addresses_primary' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'EmailAddresses',
      'rhs_table' => 'email_addresses',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'email_addr_bean_rel',
      'join_key_lhs' => 'bean_id',
      'join_key_rhs' => 'email_address_id',
      'relationship_role_column' => 'primary_address',
      'relationship_role_column_value' => '1',
    ),
    'member_accounts' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Accounts',
      'rhs_table' => 'accounts',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
    ),
    'account_cases' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Cases',
      'rhs_table' => 'cases',
      'rhs_key' => 'account_id',
      'relationship_type' => 'one-to-many',
    ),
    'account_tasks' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Tasks',
      'rhs_table' => 'tasks',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Accounts',
    ),
    'account_notes' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Notes',
      'rhs_table' => 'notes',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Accounts',
    ),
    'account_meetings' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Meetings',
      'rhs_table' => 'meetings',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Accounts',
    ),
    'account_calls' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Calls',
      'rhs_table' => 'calls',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Accounts',
    ),
    'account_emails' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Emails',
      'rhs_table' => 'emails',
      'rhs_key' => 'parent_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'parent_type',
      'relationship_role_column_value' => 'Accounts',
    ),
    'account_leads' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'Leads',
      'rhs_table' => 'leads',
      'rhs_key' => 'account_id',
      'relationship_type' => 'one-to-many',
    ),
    'account_campaign_log' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'CampaignLog',
      'rhs_table' => 'campaign_log',
      'rhs_key' => 'target_id',
      'relationship_type' => 'one-to-many',
      'relationship_role_column' => 'target_type',
      'relationship_role_column_value' => 'Accounts',
    ),
    'account_aos_quotes' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'AOS_Quotes',
      'rhs_table' => 'aos_quotes',
      'rhs_key' => 'billing_account_id',
      'relationship_type' => 'one-to-many',
    ),
    'account_aos_invoices' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'AOS_Invoices',
      'rhs_table' => 'aos_invoices',
      'rhs_key' => 'billing_account_id',
      'relationship_type' => 'one-to-many',
    ),
    'account_aos_contracts' => 
    array (
      'lhs_module' => 'Accounts',
      'lhs_table' => 'accounts',
      'lhs_key' => 'id',
      'rhs_module' => 'AOS_Contracts',
      'rhs_table' => 'aos_contracts',
      'rhs_key' => 'contract_account_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'templates' => 
  array (
    'company' => 'company',
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);