<?php 
 $GLOBALS["dictionary"]["quote_Products"]=array (
  'table' => 'quote_products',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'duplicate_merge_dom_value' => '0',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'quote_products_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'quote_products_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'quote_products_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'prod_manufacturer_c' => 
    array (
      'required' => false,
      'name' => 'prod_manufacturer_c',
      'vname' => 'Manufacturer',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => 100,
      'size' => '20',
      'options' => 'prod_manufacturer_list ',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'prod_spec_c' => 
    array (
      'required' => false,
      'name' => 'prod_spec_c',
      'vname' => 'Product Specifications',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '5',
      'cols' => '35',
    ),
    'accessories_c' => 
    array (
      'required' => false,
      'name' => 'accessories_c',
      'vname' => 'LBL_ACCESSORIES_C',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '5',
      'cols' => '35',
    ),
    'product_price_c' => 
    array (
      'required' => false,
      'name' => 'product_price_c',
      'vname' => 'LBL_PRODUCT_PRICE_C',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '11',
      'size' => '20',
      'disable_num_format' => '',
      'merge_filter' => 'disabled',
      'enable_range_search' => false,
      'min' => false,
      'max' => false,
    ),
    'image_c' => 
    array (
      'required' => false,
      'name' => 'image_c',
      'vname' => 'LBL_IMAGE_C',
      'type' => 'html',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '255',
      'size' => '20',
      'studio' => 'visible',
      'dbType' => 'text',
      'default_value' => '&lt;p&gt;bbb&lt;/p&gt;',
    ),
    'image_file_c' => 
    array (
      'required' => false,
      'name' => 'image_file_c',
      'vname' => 'LBL_IMAGE_FILE_C',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'len' => '60',
      'size' => '20',
    ),
    'uom_c' => 
    array (
      'labelValue' => 'UOM',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'uom_c',
      'vname' => 'LBL_UOM',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'SPF',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'uom_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Productsuom_c',
      'custom_module' => 'quote_Products',
    ),
    'tax_class_c' => 
    array (
      'labelValue' => 'Tax Class',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'tax_class_c',
      'vname' => 'LBL_TAX_CLASS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Taxable',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'tax_class_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Productstax_class_c',
      'custom_module' => 'quote_Products',
    ),
    'support_term_c' => 
    array (
      'labelValue' => 'Support Term',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'support_term_c',
      'vname' => 'LBL_SUPPORT_TERM',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Six_Months',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'support_term_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Productssupport_term_c',
      'custom_module' => 'quote_Products',
    ),
    'quote_product_category_quote_products' => 
    array (
      'name' => 'quote_product_category_quote_products',
      'type' => 'link',
      'relationship' => 'quote_product_category_quote_products',
      'source' => 'non-db',
      'module' => 'quote_Product_Category',
      'bean_name' => false,
      'vname' => 'LBL_QUOTE_PRODUCT_CATEGORY_QUOTE_PRODUCTS_FROM_QUOTE_PRODUCT_CATEGORY_TITLE',
      'id_name' => 'quote_product_category_quote_productsquote_product_category_ida',
    ),
    'quote_product_category_quote_products_name' => 
    array (
      'name' => 'quote_product_category_quote_products_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_QUOTE_PRODUCT_CATEGORY_QUOTE_PRODUCTS_FROM_QUOTE_PRODUCT_CATEGORY_TITLE',
      'save' => true,
      'id_name' => 'quote_product_category_quote_productsquote_product_category_ida',
      'link' => 'quote_product_category_quote_products',
      'table' => 'quote_product_category',
      'module' => 'quote_Product_Category',
      'rname' => 'name',
    ),
    'quote_product_category_quote_productsquote_product_category_ida' => 
    array (
      'name' => 'quote_product_category_quote_productsquote_product_category_ida',
      'type' => 'link',
      'relationship' => 'quote_product_category_quote_products',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_QUOTE_PRODUCT_CATEGORY_QUOTE_PRODUCTS_FROM_QUOTE_PRODUCTS_TITLE',
    ),
    'quantity_box_c' => 
    array (
      'labelValue' => 'Quantity/ Box',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'quantity_box_c',
      'vname' => 'LBL_QUANTITY_BOX',
      'type' => 'int',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => NULL,
      'min' => false,
      'max' => false,
      'id' => 'quote_Productsquantity_box_c',
      'custom_module' => 'quote_Products',
    ),
    'unit_price_c' => 
    array (
      'labelValue' => 'Unit Price',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'unit_price_c',
      'vname' => 'LBL_UNIT_PRICE',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'quote_Productsunit_price_c',
      'custom_module' => 'quote_Products',
    ),
    'team_id' => 
    array (
      'required' => '0',
      'name' => 'team_id',
      'vname' => 'LBL_TEAM_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '36',
    ),
    'team_name' => 
    array (
      'required' => '0',
      'source' => 'non-db',
      'name' => 'team_name',
      'vname' => 'LBL_TEAM_NAME',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'team_id',
      'ext2' => 'team',
      'module' => 'team',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'type_c' => 
    array (
      'labelValue' => 'Product Type',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'type_c',
      'vname' => 'LBL_TYPE',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'type_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'quote_Productstype_c',
      'custom_module' => 'quote_Products',
    ),
    'item_code_c' => 
    array (
      'labelValue' => 'Item Code',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'item_code_c',
      'vname' => 'LBL_ITEM_CODE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Productsitem_code_c',
      'custom_module' => 'quote_Products',
    ),
    'availability_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'availability_c',
      'vname' => 'LBL_AVAILABILITY',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'availability_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'quote_Productsavailability_c',
      'custom_module' => 'quote_Products',
    ),
    'currency_id' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
      'id' => 'quote_Productscurrency_id',
      'custom_module' => 'quote_Products',
    ),
    'default_pricing_formula_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'default_pricing_formula_c',
      'vname' => 'LBL_DEFAULT_PRICING_FORMULA',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'Fix_Price',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'default_pricing_formula_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'quote_Productsdefault_pricing_formula_c',
      'custom_module' => 'quote_Products',
    ),
    'pricing_factor_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'pricing_factor_c',
      'vname' => 'LBL_PRICING_FACTOR',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '8',
      'id' => 'quote_Productspricing_factor_c',
      'custom_module' => 'quote_Products',
    ),
    'vendor_part_number_c' => 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'vendor_part_number_c',
      'vname' => 'LBL_VENDOR_PART_NUMBER',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'quote_Productsvendor_part_number_c',
      'custom_module' => 'quote_Products',
    ),
  ),
  'relationships' => 
  array (
    'quote_products_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Products',
      'rhs_table' => 'quote_products',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'quote_products_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Products',
      'rhs_table' => 'quote_products',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'quote_products_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'quote_Products',
      'rhs_table' => 'quote_products',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'quote_productspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);