<?php 
 $GLOBALS["dictionary"]["EvMgr_Evs"]=array (
  'table' => 'evmgr_evs',
  'audited' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'enabled',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'evmgr_evs_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'evmgr_evs_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'evmgr_evs_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'event_type' => 
    array (
      'required' => false,
      'name' => 'event_type',
      'vname' => 'LBL_EVENT_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'Seminar',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_event_type_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'event_status' => 
    array (
      'required' => false,
      'name' => 'event_status',
      'vname' => 'LBL_EVENT_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'Planning',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_event_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'pre_material_required' => 
    array (
      'required' => false,
      'name' => 'pre_material_required',
      'vname' => 'LBL_PRE_MATERIAL_REQUIRED',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'accomodations_required' => 
    array (
      'required' => false,
      'name' => 'accomodations_required',
      'vname' => 'LBL_ACCOMODATIONS_REQUIRED',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'fire_alarm_schedule_checked' => 
    array (
      'required' => false,
      'name' => 'fire_alarm_schedule_checked',
      'vname' => 'LBL_FIRE_ALARM_SCHEDULE_CHECKED',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'post_event_commentary' => 
    array (
      'required' => false,
      'name' => 'post_event_commentary',
      'vname' => 'LBL_POST_EVENT_COMMENTARY',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '80',
    ),
    'start_date' => 
    array (
      'required' => false,
      'name' => 'start_date',
      'vname' => 'LBL_START_DATE',
      'type' => 'datetimecombo',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'dbType' => 'datetime',
      'display_default' => 'now&08:00am',
    ),
    'end_date' => 
    array (
      'required' => false,
      'name' => 'end_date',
      'vname' => 'LBL_END_DATE',
      'type' => 'datetimecombo',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'dbType' => 'datetime',
      'display_default' => 'now&05:00pm',
    ),
    'ce_hours_credit' => 
    array (
      'required' => false,
      'name' => 'ce_hours_credit',
      'vname' => 'LBL_CE_HOURS_CREDIT',
      'type' => 'int',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'num_invited' => 
    array (
      'required' => false,
      'name' => 'num_invited',
      'vname' => 'LBL_NUM_INVITED',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'num_confirmed' => 
    array (
      'required' => false,
      'name' => 'num_confirmed',
      'vname' => 'LBL_NUM_CONFIRMED',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'num_nevershowed' => 
    array (
      'required' => false,
      'name' => 'num_nevershowed',
      'vname' => 'LBL_NUM_NEVERSHOWED',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'num_participated' => 
    array (
      'required' => false,
      'name' => 'num_participated',
      'vname' => 'LBL_NUM_PARTICIPATED',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'num_graduated' => 
    array (
      'required' => false,
      'name' => 'num_graduated',
      'vname' => 'LBL_NUM_GRADUATED',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    ),
    'customer_contract' => 
    array (
      'required' => false,
      'name' => 'customer_contract',
      'vname' => 'LBL_CUSTOMER_CONTRACT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'ToBeDetermined',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'facilitator_contract' => 
    array (
      'required' => false,
      'name' => 'facilitator_contract',
      'vname' => 'LBL_FACILITATOR_CONTRACT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'ToBeDetermined',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'venue_contract' => 
    array (
      'required' => false,
      'name' => 'venue_contract',
      'vname' => 'LBL_VENUE_CONTRACT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'TBD',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'event_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'caterer_contract' => 
    array (
      'required' => false,
      'name' => 'caterer_contract',
      'vname' => 'LBL_CATERER_CONTRACT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'TBD',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'event_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'accommodations_contract' => 
    array (
      'required' => false,
      'name' => 'accommodations_contract',
      'vname' => 'LBL_ACCOMMODATIONS_CONTRACT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'TBD',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'event_contract_status_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'program_designed' => 
    array (
      'required' => false,
      'name' => 'program_designed',
      'vname' => 'LBL_PROGRAM_DESIGNED',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'insurance_certificate_obtained' => 
    array (
      'required' => false,
      'name' => 'insurance_certificate_obtained',
      'vname' => 'LBL_INSURANCE_CERTIFICATE_OBTAINED',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'material_produced' => 
    array (
      'required' => false,
      'name' => 'material_produced',
      'vname' => 'LBL_MATERIAL_PRODUCED',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'marketing_started' => 
    array (
      'required' => false,
      'name' => 'marketing_started',
      'vname' => 'LBL_MARKETING_STARTED',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'travel_and_accom' => 
    array (
      'required' => false,
      'name' => 'travel_and_accom',
      'vname' => 'LBL_TRAVEL_AND_ACCOM',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'pre_event_mailing_sent' => 
    array (
      'required' => false,
      'name' => 'pre_event_mailing_sent',
      'vname' => 'LBL_PRE_EVENT_MAILING_SENT',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'attendee_status_updated' => 
    array (
      'required' => false,
      'name' => 'attendee_status_updated',
      'vname' => 'LBL_ATTENDEE_STATUS_UPDATED',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'eval_scores_reported' => 
    array (
      'required' => false,
      'name' => 'eval_scores_reported',
      'vname' => 'LBL_EVAL_SCORES_REPORTED',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'budget_total' => 
    array (
      'required' => false,
      'name' => 'budget_total',
      'vname' => 'LBL_BUDGET_TOTAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'currency_id' => 
    array (
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
    ),
    'budget_facilitator' => 
    array (
      'required' => false,
      'name' => 'budget_facilitator',
      'vname' => 'LBL_BUDGET_FACILITATOR',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'budget_venue' => 
    array (
      'required' => false,
      'name' => 'budget_venue',
      'vname' => 'LBL_BUDGET_VENUE',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'budget_caterer' => 
    array (
      'required' => false,
      'name' => 'budget_caterer',
      'vname' => 'LBL_BUDGET_CATERER',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'budget_material' => 
    array (
      'required' => false,
      'name' => 'budget_material',
      'vname' => 'LBL_BUDGET_MATERIAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'budget_other' => 
    array (
      'required' => false,
      'name' => 'budget_other',
      'vname' => 'LBL_BUDGET_OTHER',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'facilitator_fees' => 
    array (
      'required' => false,
      'name' => 'facilitator_fees',
      'vname' => 'LBL_FACILITATOR_FEES',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '80',
    ),
    'actual_cost_total' => 
    array (
      'required' => false,
      'name' => 'actual_cost_total',
      'vname' => 'LBL_ACTUAL_COST_TOTAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'actual_cost_facilitator' => 
    array (
      'required' => false,
      'name' => 'actual_cost_facilitator',
      'vname' => 'LBL_ACTUAL_COST_FACILITATOR',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'actual_cost_venue' => 
    array (
      'required' => false,
      'name' => 'actual_cost_venue',
      'vname' => 'LBL_ACTUAL_COST_VENUE',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'actual_cost_caterer' => 
    array (
      'required' => false,
      'name' => 'actual_cost_caterer',
      'vname' => 'LBL_ACTUAL_COST_CATERER',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'actual_cost_material' => 
    array (
      'required' => false,
      'name' => 'actual_cost_material',
      'vname' => 'LBL_ACTUAL_COST_MATERIAL',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'actual_cost_other' => 
    array (
      'required' => false,
      'name' => 'actual_cost_other',
      'vname' => 'LBL_ACTUAL_COST_OTHER',
      'type' => 'currency',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
    ),
    'post_event_mailing_sent' => 
    array (
      'required' => false,
      'name' => 'post_event_mailing_sent',
      'vname' => 'LBL_POST_EVENT_MAILING_SENT',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'No',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'evmgr_pogress_check_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'evmgr_evparts_evmgr_evs' => 
    array (
      'name' => 'evmgr_evparts_evmgr_evs',
      'type' => 'link',
      'relationship' => 'evmgr_evparts_evmgr_evs',
      'source' => 'non-db',
      'module' => 'EvMgr_EvParts',
      'bean_name' => 'EvMgr_EvParts',
      'side' => 'right',
      'vname' => 'LBL_EVMGR_EVPARTS_EVMGR_EVS_FROM_EVMGR_EVPARTS_TITLE',
    ),
    'evmgr_evs_evmgr_venrms' => 
    array (
      'name' => 'evmgr_evs_evmgr_venrms',
      'type' => 'link',
      'relationship' => 'evmgr_evs_evmgr_venrms',
      'source' => 'non-db',
      'module' => 'EvMgr_VenRms',
      'bean_name' => 'EvMgr_VenRms',
      'vname' => 'LBL_EVMGR_EVS_EVMGR_VENRMS_FROM_EVMGR_VENRMS_TITLE',
    ),
    'evmgr_evs_activities_tasks' => 
    array (
      'name' => 'evmgr_evs_activities_tasks',
      'type' => 'link',
      'relationship' => 'evmgr_evs_activities_tasks',
      'source' => 'non-db',
      'module' => 'Tasks',
      'bean_name' => 'Task',
      'vname' => 'LBL_EVMGR_EVS_ACTIVITIES_TASKS_FROM_TASKS_TITLE',
    ),
    'evmgr_evs_contacts' => 
    array (
      'name' => 'evmgr_evs_contacts',
      'type' => 'link',
      'relationship' => 'evmgr_evs_contacts',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'vname' => 'LBL_EVMGR_EVS_CONTACTS_FROM_CONTACTS_TITLE',
    ),
    'evmgr_evs_documents' => 
    array (
      'name' => 'evmgr_evs_documents',
      'type' => 'link',
      'relationship' => 'evmgr_evs_documents',
      'source' => 'non-db',
      'module' => 'Documents',
      'bean_name' => 'Document',
      'vname' => 'LBL_EVMGR_EVS_DOCUMENTS_FROM_DOCUMENTS_TITLE',
    ),
    'evmgr_evs_accounts' => 
    array (
      'name' => 'evmgr_evs_accounts',
      'type' => 'link',
      'relationship' => 'evmgr_evs_accounts',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_EVMGR_EVS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
    ),
    'evmgr_evs_activities_meetings' => 
    array (
      'name' => 'evmgr_evs_activities_meetings',
      'type' => 'link',
      'relationship' => 'evmgr_evs_activities_meetings',
      'source' => 'non-db',
      'module' => 'Meetings',
      'bean_name' => 'Meeting',
      'vname' => 'LBL_EVMGR_EVS_ACTIVITIES_MEETINGS_FROM_MEETINGS_TITLE',
    ),
    'evmgr_evs_activities_notes' => 
    array (
      'name' => 'evmgr_evs_activities_notes',
      'type' => 'link',
      'relationship' => 'evmgr_evs_activities_notes',
      'source' => 'non-db',
      'module' => 'Notes',
      'bean_name' => 'Note',
      'vname' => 'LBL_EVMGR_EVS_ACTIVITIES_NOTES_FROM_NOTES_TITLE',
    ),
    'evmgr_evs_activities_calls' => 
    array (
      'name' => 'evmgr_evs_activities_calls',
      'type' => 'link',
      'relationship' => 'evmgr_evs_activities_calls',
      'source' => 'non-db',
      'module' => 'Calls',
      'bean_name' => 'Call',
      'vname' => 'LBL_EVMGR_EVS_ACTIVITIES_CALLS_FROM_CALLS_TITLE',
    ),
    'evmgr_evs_activities_emails' => 
    array (
      'name' => 'evmgr_evs_activities_emails',
      'type' => 'link',
      'relationship' => 'evmgr_evs_activities_emails',
      'source' => 'non-db',
      'module' => 'Emails',
      'bean_name' => 'Email',
      'vname' => 'LBL_EVMGR_EVS_ACTIVITIES_EMAILS_FROM_EMAILS_TITLE',
    ),
    'evmgr_evs_evmgr_pgms' => 
    array (
      'name' => 'evmgr_evs_evmgr_pgms',
      'type' => 'link',
      'relationship' => 'evmgr_evs_evmgr_pgms',
      'source' => 'non-db',
      'module' => 'EvMgr_Pgms',
      'bean_name' => 'EvMgr_Pgms',
      'vname' => 'LBL_EVMGR_EVS_EVMGR_PGMS_FROM_EVMGR_PGMS_TITLE',
    ),
    'evmgr_evs_opportunities' => 
    array (
      'name' => 'evmgr_evs_opportunities',
      'type' => 'link',
      'relationship' => 'evmgr_evs_opportunities',
      'source' => 'non-db',
      'module' => 'Opportunities',
      'bean_name' => 'Opportunity',
      'vname' => 'LBL_EVMGR_EVS_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
      'id_name' => 'evmgr_evs_opportunitiesopportunities_ida',
    ),
    'evmgr_evs_opportunities_name' => 
    array (
      'name' => 'evmgr_evs_opportunities_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_EVMGR_EVS_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
      'save' => true,
      'id_name' => 'evmgr_evs_opportunitiesopportunities_ida',
      'link' => 'evmgr_evs_opportunities',
      'table' => 'opportunities',
      'module' => 'Opportunities',
      'rname' => 'name',
      'required' => true,
    ),
    'evmgr_evs_opportunitiesopportunities_ida' => 
    array (
      'name' => 'evmgr_evs_opportunitiesopportunities_ida',
      'type' => 'link',
      'relationship' => 'evmgr_evs_opportunities',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_EVMGR_EVS_OPPORTUNITIES_FROM_EVMGR_EVS_TITLE',
    ),
  ),
  'relationships' => 
  array (
    'evmgr_evs_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'EvMgr_Evs',
      'rhs_table' => 'evmgr_evs',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'evmgr_evs_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'EvMgr_Evs',
      'rhs_table' => 'evmgr_evs',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'evmgr_evs_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'EvMgr_Evs',
      'rhs_table' => 'evmgr_evs',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'evmgr_evspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => false,
);