<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN quote_Quotes
 */

require_once('include/SugarObjects/templates/issue/Issue.php');

class quote_Quotes_sugar extends Issue {
	var $new_schema = true;
	var $module_dir = 'quote_Quotes';
	var $object_name = 'quote_Quotes';
	var $table_name = 'quote_quotes';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $quote_quotes_number;
		var $type;
		var $status;
		var $priority;
		var $resolution;
		var $work_log;
		var $quotation_status;
		var $tax;
		var $discount;
		var $discount_checkbox;
		var $insurance;
		var $terms_conditions;
		var $quotation_category;
		var $covering_letter;
		var $insurance_checkbox;
		var $quote_products_id_c;
		var $product1;
		var $prod1_quantity;
		var $prod1_cost;
		var $quote_products_id1_c;
		var $sm_quotes_id_c;
		var $quote_products_id2_c;
		var $product2;
		var $quote_products_id3_c;
		var $product3;
		var $quote_products_id4_c;
		var $product4;
		var $quote_products_id5_c;
		var $product5;
		var $quote_products_id6_c;
		var $product6;
		var $quantity1;
		var $quantity2;
		var $quote_products_id7_c;
		var $product7;
		var $quantity3;
		var $quote_products_id8_c;
		var $product8;
		var $quantity4;
		var $quantity5;
		var $quote_products_id9_c;
		var $product9;
		var $quantity6;
		var $quote_products_id10_c;
		var $product10;
		var $quantity7;
		var $quantity8;
		var $quantity9;
		var $product11;
		var $quantity10;
		var $product12;
		var $product13;
		var $quantity11;
		var $quantity12;
		var $quantity13;
		var $quantity14;
		var $quantity15;
		var $product14;
		var $quantity16;
		var $product15;
		var $quantity17;
		var $quantity18;
		var $product16;
		var $quantity19;
		var $product17;
		var $product18;
		var $quantity20;
		var $product19;
		var $quantity21;
		var $quantity22;
		var $quantity23;
		var $quantity24;
		var $quantity25;
		var $product20;
		var $quantity26;
		var $quantity27;
		var $product21;
		var $quantity28;
		var $product22;
		var $product23;
		var $quantity29;
		var $product24;
		var $quantity30;
		var $product25;
		var $quantity31;
		var $quantity32;
		var $quantity33;
		var $quantity34;
		var $quantity35;
		var $product26;
		var $product27;
		var $product28;
		var $product29;
		var $product30;
		var $product31;
		var $product32;
		var $product33;
		var $product34;
		var $product35;
		var $cost1;
		var $cost3;
		var $cost4;
		var $cost5;
		var $cost6;
		var $cost7;
		var $cost8;
		var $cost9;
		var $cost10;
		var $price1;
		var $price2;
		var $price3;
		var $price4;
		var $price5;
		var $price6;
		var $price7;
		var $price8;
		var $price9;
		var $price10;
		var $price11;
		var $price12;
		var $price13;
		var $price14;
		var $price15;
		var $price16;
		var $price17;
		var $price18;
		var $price19;
		var $price20;
		var $price21;
		var $price22;
		var $price23;
		var $price24;
		var $price25;
		var $quote_type;
		var $spares;
		var $currency;
		var $currency_id;
		var $freight_charge;
		var $sales_quote_no;
		var $service_quotes_no;
		var $cost2;
		var $quotation_date;
		function quote_Quotes_sugar(){	
		parent::Issue();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>