<?php
$dictionary["Account"]["fields"]["av_contact_c"] = array (
	'name' => 'av_contact_c',
	'label' => 'LBL_AV_CONTACT',
	'type' => 'relate',
	'default_value' => false,
	'comments' => '',
	'help' => '',
	'massupdate' => false,
	'required' => false,
	'reportable' => true,
	'importable' => 'true',
	'duplicate_merge' => 'disabled',
	'duplicate_merge_dom_value' => '0',
	'studio' => 'visible',
	'audited' => false,
	'max_size' => '255',
	'ext1' => '',
	'ext3' => '',
	'calculated' => false,
	'source' => 'non-db',
	'id_name' => 'contact_id4_c',
	'ext2' => 'Contacts',
	'module' => 'Contacts',
	'rname' => 'name',
	'quicksearch' => 'enabled',
	'studio' => 'visible',
);
?>